/* eslint-disable no-unused-vars */
import React, { useState } from 'react';
import '@fortawesome/fontawesome-free/css/all.min.css';

const Provider = () => {
  const [visibleTable, setVisibleTable] = useState('table1');
  const [currentPage, setCurrentPage] = useState({ table1: 1, table2: 1, table3: 1 });
  const [sortConfig, setSortConfig] = useState({ table1: { key: null, direction: 'asc' }, table2: { key: null, direction: 'asc' }, table3: { key: null, direction: 'asc' } });
  const [filterText, setFilterText] = useState({ table1: '', table2: '', table3: '' });
  const [selectedLGA, setSelectedLGA] = useState({ table1: '', table2: '', table3: '' });
  const rowsPerPage = 20;

  const table1Data = [
    ["ORILE-AGEGE GENERAL HOSPITAL", "OLD OTA ROAD, OFF LAGOS-ABEOKUTA EXPRESSWAY, AGEGE , LAGOS", "AGEGE"],
    ["ANCILLA CATHOLIC HOSPITAL, AGEGE", "113, ODUMOSU CLOSE, IFAKO, AGEGE", "AGEGE"],
    ["ADAMS CLINIC AND MATERNITY CENTER", "16, ADEYEMI STREET, MOSHALASHI BUS-STOP, AGEGE", "AGEGE"],
    ["ALL SOULS INFIRMARY LTD", "8, CHURCH STREET, ELERE, AGEGE", "AGEGE"],
    ["AL-IMAAN HOSPITAL", "20, SURULERE ROAD, DOPEMU, AGEGE", "AGEGE"],
    ["BETTA HOSPITAL", "9/11 COKER STREET, ORILE, AGEGE, LAGOS", "AGEGE"],
    ["BIO BATAM HOSPITAL", "53, TIJANI STREET, IYANA IPAJA", "AGEGE"],
    ["DUNIA HOSPITAL LTD", "45, OKO-OBA ROAD, AGEGE, AGEGE, LAGOS", "AGEGE"],
    ["GOODNESS MEDICAL CENTRE, AGEGE", "24, SHABA STREET, OPPOSITE BABATUNDE RAJI FASHOLA TRAIN STATION, AGEGE", "AGEGE"],
    ["HEARTLAND ALLIANCE LTD/GTE", "25, ADEYEMI STREET, OFF ANUOLUWAPO STREET, AGEGE, LAGOS", "AGEGE"],
    ["MOBONIKE HOSPITAL", "33, SURULERE STREET, DOPEMU, LAGOS, LAGOS", "AGEGE"],
    ["MOLAYO MEDICAL CENTER", "20, AKINLEYE STREET, OKO-OBA, AGEGE, LAGOS", "AGEGE"],
    ["NEW ALPHA MEDICAL CENTRE", "26, OSHUNDAIRO STREET, OFF LAGOS-ABEOKUTA EXPRESS WAY, ARAROMI BUS-STOP, IYANA-IPAJA, LAGOS", "AGEGE"],
    ["NEW MERIT HOSPITAL", "23, LADOJE STREET, GENGETO, AGEGE, LAGOS", "AGEGE"],
    ["OLIVE MEDICARE HOSPITAL", "6, GHOLUS CLOSE, DOPEMU", "AGEGE"],
    ["PROMISE MEDICAL CENTRE", "132 DOPEMU ROAD, DOPEMU, AGEGE, LAGOS", "AGEGE"],
    ["R-JOLAD HOSPITAL (SALEM HOUSE)", "23/24 OMOTOYE ESTATE ROAD, OFF IPAJA ROAD, MULERO BUS-STOP, ORILE-AGEGE", "AGEGE"],
    ["TODAY MEDICHEALTH SERVICES", "37, OWOLABI OMOTOYE STREET, IYANA ORILE JUNCTION, OFF IPAJA ROAD, AGEGE, LAGOS", "AGEGE"],
    ["VETA HOSPITALS LTD", "1-3, VETA CLOSE,  LAGOS-ABEOKUTA EXPRESS WAY, ARAROMI BUS-STOP, IYANA-IPAJA, LAGOS", "AGEGE"],
    ["ODUMBAKU PRIMARY HEALTHCARE CENTER", "36, OPEOLU STREET, ORILE-AGEGE", "AGEGE"],
    ["SANGO PRIMARY HEALTHCARE CENTRE", "BALOGUN STREET, PEN CINEMA, AGEGE", "AGEGE"],
    ["AJEROMI GENERAL HOSPITAL, AJEGUNLE", "6, CARDOSO STREET, AJEGUNLE, LAGOS", "AJEROMI-IFELODUN"],
    ["ABBEY MEDICAL CENTRE", "74, IDOWU STREET, OLODI APAPA, LAGOS,", "AJEROMI-IFELODUN"],
    ["ALL SOULS' HOSPITAL", "255 OJO ROAD, SURU ALABA, MILE 2, AJEGUNLE, APAPA, LAGOS", "AJEROMI-IFELODUN"],
    ["BAYO OGUNRO MEMORIAL HOSPITAL", "158, KIRIKIRI ROAD, OLODI-APAPA, AJEROMI IFELODUN, LAGOS", "AJEROMI-IFELODUN"],
    ["BEEBAT MEDICAL CENTER", "2, JIMOH OJORA STREET, OFF OJO ROAD, AJEGUNLE, APAPA", "AJEROMI-IFELODUN"],
    ["DE-OVERCOMING GRACE HOSPITAL", "19, MUDA STREET, AMUKOKO, , LAGOS", "AJEROMI-IFELODUN"],
    ["FALETI MEDICAL CENTRE", "98 BAALE STREET, OLODI, APAPA, LAGOS", "AJEROMI-IFELODUN"],
    ["JIM-SAM HOSPITAL & MATERNITY LTD", "22, GASKIYA COLLEGE ROAD, IJORA-BADIA, LAGOS", "AJEROMI-IFELODUN"],
    ["KENNY MEDICAL CENTRE", "209, KIRIKIRI ROAD, OLODI-APAPA", "AJEROMI-IFELODUN"],
    ["NATAFOD CONSULTANT HOSPITAL", "104, CEMETRY ROAD, MOSAFEJO, AMUKOKO, LAGOS", "AJEROMI-IFELODUN"],
    ["PATOL MEDICAL CENTRE", "48, SWAMP STREET, APAPA, AJEROMI IFELODUN, LAGOS", "AJEROMI-IFELODUN"],
    ["SONEX HOSPITAL", "3, EMORDI STREET, OLODI APAPA", "AJEROMI-IFELODUN"],
    ["AKERE PRIMARY HEALTHCARE CENTRE", "106, BAALE STREET, AJEGUNLE, AJEROMI", "AJEROMI-IFELODUN"],
    ["AMUKOKO PRIMARY HEALTHCARE CENTRE", "1, MOSAFEJO ROAD, TAXI PARK, AMUKOKO", "AJEROMI-IFELODUN"],
    ["LAYENI PRIMARY HEALTHCARE CENTRE", "224, OLD OJO ROAD", "AJEROMI-IFELODUN"],
    ["ALIMOSHO GENERAL HOSPITAL", "LASU/ISHERI ROAD, IGANDO, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["A'S RADIANCE HOSPITAL & MATERNITY HOME", "5, ADERU AJITE STREET, OPPOSITE BENEFACTOR STREET, AIT ROAD, ALAGBADO", "ALIMOSHO"],
    ["A-ROCK MEDICAL CENTER", "21, POPOOLA STREET, OJUGBELE, IKOLA, COMMAND, LAGOS", "ALIMOSHO"],
    ["ADEBAYO SPECIALIST HOSPITAL", "14,AJENIFUJA STREET, GOVERNOR'S ROAD, IKOTUN, LAGOS", "ALIMOSHO"],
    ["AGAPE MEDICAL CENTRE", "16, OGUNBIYI ILO STREET, OLUDE BUS STOP,  IPAJA, LAGOS", "ALIMOSHO"],
    ["AKANBI MEMORIAL HOSPITAL", "27, YETUNDE KUFORIJI STREET, I.B.T.C AYOBO, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["ARABA MEDICAL CENTRE", "122, EKORO AGBELEKALE ROAD, ABULE-EGBA, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["BEE HESS HOSPITAL", "155, AKOWONJO ROAD, EGBEDA, LAGOS", "ALIMOSHO"],
    ["BIENSANTE HOSPITAL", "9, ALAKA STREET, OFF BAMMEKE ROAD, SHASHA, AKOWONJO", "ALIMOSHO"],
    ["BROAD HOSPITAL", "13, FEHINTOLA STREET, IKOTUN, IGANDO-IKOTUN, LAGOS", "ALIMOSHO"],
    ["CAREPOINT CLINICS", "7-9, OGUNLANA STREET, OFF AKOWONJO ROAD, EGBEDA, LAGOS", "ALIMOSHO"],
    ["CAREWAY HOSPITAL & MATERNITY", "14, ORELOPE STREET, EGBEDA, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["CRYSTAL SPECIALIST HOSPITAL", "148/150 AKOWONJO ROAD, EGBEDA, , LAGOS", "ALIMOSHO"],
    ["EL-DUNAMIS MEDICAL CENTRE", "6, KING SOLOMON STREET, OLOGURO, AKESAN, LAGOS", "ALIMOSHO"],
    ["FIRSTLINE HOSPITAL, AYOBO", "142, CAMP DAVID ROAD, AYOBO", "ALIMOSHO"],
    ["FIRST U-TURN HOSPITAL", "2, RISIKAT MAJARO STREET, OFF LAGOS-ABEOKUTA EXPRESS WAY, ABULE-EGBA", "ALIMOSHO"],
    ["FOUNTAIN OF HEALTH HOSPITAL/MATERNITY HOME", "5-6, ONA-IWA MIMO STREET, BY NNPC FUEL STATION, ORI-OKE EJIGBO", "ALIMOSHO"],
    ["FUNBI MEDICAL CENTRE", "10A, KOLAWOLE OTUN CLOSE, MOSHALASHI BUS-STOP, ALAGBADO, LAGOS", "ALIMOSHO"],
    ["GLAD TIDINGS MEDICAL CENTER", "1, AMUSA ALABI STREET (OLD CHURCH STREET), OFF GBADAMOSI OPESA STREET, IPAJA", "ALIMOSHO"],
    ["GUARDIAN HEALTH HOSPITAL", "182, EKORO ROAD, ABULE-EGBA, LAGOS", "ALIMOSHO"],
    ["HAMKAD HOSPITAL NIGERIA LIMITED", "39, OLAWALE COLE STREET, ABULE-EGBA, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["ICONIC CARE HOSPITAL", "75, ISUTI ROAD, EGAN", "ALIMOSHO"],
    ["JUMOKE HOSPITAL AND MATERNITY", "98, IFELODUN STREET, EJIGBO, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["KROWN HOSPITAL", "11, ALHAJI SEKONI STREET, OFF ALIMOSHO ROAD, IYANA-IPAJA , LAGOS", "ALIMOSHO"],
    ["KUNLADE HOSPITAL", "7, OPEKI ROAD, IPAJA, LAGOS, LAGOS", "ALIMOSHO"],
    ["LIFE ANCHOR HOSPITAL", "17A BAMISHILE STREET, SHASHA, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["LIFE FOUNT MEDICAL AND DIAGNOSTIC CENTRE LTD", "103, MOSHALASHI ROAD, SHIMA BUS STOP, EGAN, IGANDO, LAGOS", "ALIMOSHO"],
    ["LIGHT HOSPITAL & MATERNITY HOME LTD", "15, OLUMIDE ONANUBI STREET, ALIMOSHO BUS STOP, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["LOTA MEDICAL CENTRE", "1, MOJISOLAABASS STREET , ISHERI-OLOFIN, OFF LASU ROAD, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["MARY THE QUEEN HOSPITAL LTD", "29, BABALOLA STREET, AKOWONJO, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["MEDISERVICES COMMUNITY HOSPITAL", "28, DAVID OGUNDELE STREET, IPAJA, LAGOS", "ALIMOSHO"],
    ["MERCY STRIPES SPECIALIST HOSPITAL", "30, PHILIP TAIWO STREET, ORISUMBARA-SHASHA, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["MERCYGATE HOSPITAL", "24, OGUNLANA STREET, EGBEDA, EGBEDA, LAGOS", "ALIMOSHO"],
    ["MOTHER TERESA MEDICAL CENTER", "107, LIASU ROAD, IDIMU, EGBE, LAGOS", "ALIMOSHO"],
    ["MOUNT PISGAH HOSPITAL LIMITED", "1, SAMUEL SODE STREET, OFF CELE EGBE ROAD, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["OKIKI CLINIC & MATERNITY HOSPITAL", "18, OLA-SHEU STREET, LAGOS", "ALIMOSHO"],
    ["OWOLOLA BETHEL HOSPITAL", "2, TIAMIYU STREET, HILL TOP ESTATE, ABORU VILLAGE, IYANA-IPAJA, LAGOS", "ALIMOSHO"],
    ["PAKAL MEDICAL CENTER", "12, AGBO AKOMOLAFE STREET, UNITY ESTATE, EGBEDA", "ALIMOSHO"],
    ["PEACEFUL HEALTH HOSPITAL AND MATERNITY HOME", "60, IJAGEMO ROAD, IJEGUN, LAGOS", "ALIMOSHO"],
    ["PERISCOPE HOSPITAL", "14, MA OKE STREET, DIAMOND ESTATE, ISHERI-LASU ROAD, LAGOS", "ALIMOSHO"],
    ["PRINCE & PRINCESS HOSPITALS", "PLOT 75, 1ST AVENUE, 12 ROAD, GOWON ESTATE, EGBEDA", "ALIMOSHO"],
    ["ROYAL SALVATION HOSPITAL", "31, ROAD JUNCTION, GOWON ESTATE, EGBEDA.", "ALIMOSHO"],
    ["SANTA MARIA HOSPITAL", "8, SANTA MARIA STREET, EGAN, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["SHARYOR MEDICAL CENTRE", "8, OLUSEGUN BADEJO STREET, AYOBO", "ALIMOSHO"],
    ["SOLAD MEDICAL CENTER", "16, MARIA STREET, BARUWA, IPAJA, LAGOS", "ALIMOSHO"],
    ["SILVERLINE HOSPITALS", "12, AYETORO ROAD, OLD NEPA OFFICE BUS STOP, AYOBO", "ALIMOSHO"],
    ["ST. MICHAEL'S HOSPITAL", "KM 35/972, LAGOS-ABEOKUTA EXPRESS ROAD, BESIDE SAW-MILL, ALAKUKO", "ALIMOSHO"],
    ["SUBOL HOSPITAL LIMITED", "16/17 OBA AMUSAN AVENUE, IDIMU, LAGOS", "ALIMOSHO"],
    ["SUMMIT HOSPITAL", "34 OLUWATOYIN STREET, SHASHA, AKOWONJO, LAGOS", "ALIMOSHO"],
    ["TALENT SPECIALIST HOSPITAL", "PLOT 440, 4TH AVENUE, F.H.A GOWON ESTATE, EGBEDA, LAGOS", "ALIMOSHO"],
    ["TENDER TOUCH HOSPITAL", "12, EJIGBO ROAD, ORISUNBARE, SHASHA", "ALIMOSHO"],
    ["TIP TOP SOLUTION HOSPITAL", "4, KWARU WAY, OFF ABARANJE ROAD, IKOTUN", "ALIMOSHO"],
    ["TONAJIB HOSPITAL", "46, MARIA IBIRONKE STREET, IKOTUN, IKOTUN, LAGOS", "ALIMOSHO"],
    ["VINEYARD HOSPITALS LIMITED", "4, GBEMI OGUNDEYI STREET, IDIMU, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["WATERFALLS HOSPITAL & MATERNITY, IKOTUN", "86B, IGANDO ROAD, BY MOSHALASHI BUS STOP, IKOTUN", "ALIMOSHO"],
    ["WESTCARE SPECIALIST HOSPITAL", "32, SAMUEL STREET, VULCANIZER BUS STOP, AKOWONJO, LAGOS", "ALIMOSHO"],
    ["AKOWONJO PRIMARY HEALTHCARE CENTRE", "98, AKOWONJO ROAD, VULCANIZER BUS-STOP, AKOWONJO, LAGOS", "ALIMOSHO"],
    ["IKOTUN PRIMARY HEALTHCARE CENTRE", "IKOTUN-IDIMU ROAD, OPPOSITE ECO BANK, IKOTUN, LAGOS", "ALIMOSHO"],
    ["IPAJA PRIMARY HEALTHCARE CENTRE", "AYOBO IPAJA SECRETARIAT, IGBOGILA, IPAJA, LAGOS", "ALIMOSHO"],
    ["ISHERI-OLOFIN PRIMARY HEALTHCARE CENTRE", "LASU-IBA ROAD, BY ISHERI-OLOFIN ROUNDABOUT, ISHERI, LAGOS", "ALIMOSHO"],
    ["MEIRAN PRIMARY HEALTHCARE CENTRE", "1, MEIRAN ROAD, MEIRAN BUS STOP, ALIMOSHO, LAGOS", "ALIMOSHO"],
    ["OKE-ODO PRIMARY HEALTHCARE CENTER", "5, OLD OTA ROAD, ILE-EPO, OKE-ODO", "ALIMOSHO"],
    ["ORISUMBARE PRIMARY HEALTHCARE CENTRE", "85, EJIGBO ROAD, ORISUMBARE,  LAGOS", "ALIMOSHO"],
    ["RAUF AREGBESOLA PRIMARY HEALTHCARE CENTRE", "1, POWER LINE ROAD, OKUNOLA, LAGOS", "ALIMOSHO"],
    ["G & T NURSING HOME", "BLOCK 50, PLOT 13, IDOWU BABAFEMI STREET, OFF AIT ROAD, ALAGBADO.", "ALIMOSHO"],
    ["HEBREWLAND MATERNITY HOME", "2, ANOMO STREET, OFF ASALU BUS STOP, ABARANJE, IKOTUN", "ALIMOSHO"],
    ["LIFE PILLAR CLIINIC AND MATERNIITY HOME", "4, KING DAVID AVENUE, RAINBOW BUS STOP, IJAGEMO", "ALIMOSHO"],
    ["AMUWO MEDICAL CENTER LTD", "PLOT 343, HOUSE 19, DURBAR ROAD, AMUWO ODOFIN ESTATE, MILE 2", "AMUWO-ODOFIN"],
    ["FIRSTLINE HOSPITAL, FESTAC", "2ND AVENUE, HOUSE 14, BY 207 JUNCTION, FESTAC", "AMUWO-ODOFIN"],
    ["GODSPOWER HOSPITAL", "321 ROAD, C CLOSE, HOUSE 7, FESTAC", "AMUWO-ODOFIN"],
    ["GOLDEN CROSS INFIRMARY HOSPITAL & MATERNITY", "2ND AVENUE, 22 ROAD, FESTAC TOWN, AMUWO-ODOFIN, LAGOS", "AMUWO-ODOFIN"],
    ["PANOX HOSPITAL", "PLOT 920B, RAJI RASAK ESTATE ROAD, AMUWO ODOFIN", "AMUWO-ODOFIN"],
    ["RHOWIL TOTAL CARE MEDICAL CENTRE", "PLOT 3, BLOCK 7, SITE G, SATELLITE TOWN", "AMUWO-ODOFIN"],
    ["SIRONA HOSPITAL", "HSE 9, N-CLOSE, 1ST AVENUE, FESTAC TOWN", "AMUWO-ODOFIN"],
    ["FESTAC PRIMARY HEALTHCARE CENTRE", "41 ROAD, FESTAC.", "AMUWO-ODOFIN"],
    ["AGBOJU PRIMARY HEALTHCARE CENTRE", "5, OWOTEMI CLOSE, AGBOJU", "AMUWO-ODOFIN"],
    ["SATELLITE PRIMARY HEALTHCARE CENTRE", "ASSEMBLY ROAD, SATELLITE TOWN, LAGOS", "AMUWO-ODOFIN"],
    ["GENERAL HOSPITAL, APAPA", "16, IBIKUNLE AKITOYE STREET, OFF RANDLE ROAD, APAPA, LAGOS", "APAPA"],
    ["ETERNAL LIFE HOSPITAL", "1 ASHIMOWO ABEO STREET, ORILE, APAPA, LAGOS", "APAPA"],
    ["ORANGE HEALTH MEDICAL CENTRE", "127 IDEWU STREET, OLODI-APAPA", "APAPA"],
    ["SASEUN HOSPITAL AND MATERNITY", "14, GOD IN ACTION AVENUE, OFF WILMER BRIDGE, AJEGUNLE, APAPA", "APAPA"],
    ["ST. CHARLES INFIRMARY MEDICAL CENTRE", "36, OSHO DRIVE, OFF KIRIKIRI ROAD, BY 2ND BENUE BUS STOP, OLODI-APAPA", "APAPA"],
    ["ST. MILLA HOSPITAL", "19 A, LADIPO OLUWOLE STREET, APAPA GRA, APAPA, LAGOS", "APAPA"],
    ["SYBAN MEDICAL CENTRE", "33 ADEKUNLE DEEN STREET, SARI-IGANMU, APAPA, LAGOS", "APAPA"],
    ["IJORA OLOYE PRIMARY HEALTHCARE CENTRE", "47, IJORA OLOYE STR, IJORA 7UP", "APAPA"],
    ["OLOJOWON PRIMARY HEALTHCARE CENTRE", "41, GASKIYA COLLEGE ROAD, BADIA, APAPA-IGANMU, LAGOS", "APAPA"],
    ["GENERAL HOSPITAL, BADAGRY", "HOSPITAL ROAD, PMB 1003, BADAGRY, LAGOS", "BADAGRY"],
    ["ADEBAYO LIVING TOWER HOSPITAL", "6/8 ADEBAYO OJAJUNI STREET, OFF KOMUYE BUS STOP, IMEKE, LAGOS", "BADAGRY"],
    ["AJARA MEDICAL CENTRE", "3, DAUDA BIOKU STREET, AJARA-TOPA, BADAGRY", "BADAGRY"],
    ["APPLEYARD MEDICAL CENTRE", "KM 34 LAGOS-BADAGRY EXPRESSWAY, AMUNIPO STREET, IBIYE, BADAGRY, LAGOS", "BADAGRY"],
    ["CARE GIVERS HOSPITAL", "20, LAWAL'S PLACE, TORIKOH ROAD, BADAGRY, LAGOS", "BADAGRY"],
    ["CHRIST FOUNDATION HOSPITAL", "82, ALHAJA SINOTU STREET, MOROGBO-AGBARA, BADAGRY EXPRESS ROAD, LAGOS", "BADAGRY"],
    ["DEELACS MEDICAL CENTRE", "11, MAGBON ROAD, BADAGRY EXPRESSWAY, MAGBON", "BADAGRY"],
    ["GOD'S FAVOURITE HOSPITAL", "1, FAVOUR HOSPITAL ROAD, MTN BUS STOP, ALONG BADAGRY EXPRESS WAY, BADAGRY", "BADAGRY"],
    ["IBIJOLA MEDICAL CENTRE", "OFF KM 34 LAGOS BADAGRY EXPRESSWAY, UNITY ESTATE, GADDA, IBIYE, , OLORUNDA LCDA, BADAGRY, LAGOS", "BADAGRY"],
    ["MORAYO HOSPITAL", "1, MORAYO LANE, AJIDO, IMEKE, BADAGRY", "BADAGRY"],
    ["OLA-OKI MEDICAL CENTER", "KM 53 LAGOS-BADAGRY EXPRESSWAY, IBEREKO, BADAGRY", "BADAGRY"],
    ["THE GREAT PHYSICIAN HOSPITAL", "3, NIYI ADEBULE STREET, BADAGRY, LAGOS", "BADAGRY"],
    ["WELL EAGLE HEALTH SERVICES LTD", "BEHIND RCCG (GRACELAND PARISH), JAH MICHAEL BUS-STOP, MAGBON, BADAGRY", "BADAGRY"],
    ["AJARA PRIMARY HEALTHCARE CENTRE", "1, WANDE STREET, ILUDA MANGO, AJARA", "BADAGRY"],
    ["APA PRIMARY HEALTHCARE CENTRE", "APA COMMUNITY, BADAGRY", "BADAGRY"],
    ["MARINA PRIMARY HEALTHCARE CENTRE", "MARKET ROAD, AWHAJIGON QRTS, MARINA, BADAGRY", "BADAGRY"],
    ["POTA PRIMARY HEALTHCARE CENTRE", "POTA IKOGA, BADAGRY", "BADAGRY"],
    ["ILADO PRIMARY HEALTHCARE CENTER", "ILADO TOWN", "BADAGRY"],
    ["AGBOWA GENERAL HOSPITAL", "26, HOSPITAL ROAD, OFF IKOSI ROAD, AGBOWA, LAGOS", "EPE"],
    ["FEDERAL MEDICAL CENTER, EPE", "1, HOSPITAL ROAD, EPE, LAGOS", "EPE"],
    ["KETU EJINRIN GENERAL HOSPITAL", "EJINRIN ROAD, KETU-EJINRIN, KETU, LAGOS", "EPE"],
    ["MOUNT PARAN HOSPITAL", "6, IDOWU APETE STREET, OFF PELEYEJU STREET, URAKA, EPE", "EPE"],
    ["AGBOWA PRIMARY HEALTHCARE CENTRE", "83/85 IKOSI BEACH ROAD, AGBOWA, IKOSI-EJIRIN, LAGOS", "EPE"],
    ["EPE PRIMARY HEALTHCARE CENTRE", "ITA-OPO/ITA MARUN ROAD, ALONG EPE-IJEBU ODE ROAD, , LAGOS", "EPE"],
    ["EREDO PRIMARY HEALTHCARE CENTRE", "EREDO LCDA SECRETARIAT,ALONG IJEBU –ODE ROAD EREDO, EREDO, LAGOS", "EPE"],
    ["GENERAL HOSPITAL, ODAN", "1/3 BROAD STREET , LAGOS ISLAND, LAGOS ISLAND, LAGOS", "ETI-OSA"],
    ["LAGOS ISLAND MATERNITY HOSPITAL", "CAMPBELL STREET, LAGOS ISLAND, LAGOS", "ETI-OSA"],
    ["MASSEY STREET CHILDREN'S HOSPITAL", "MASSEY STREET, LAGOS ISLAND, LAGOS ISLAND, LAGOS", "ETI-OSA"],
    ["ONIKAN HEALTH CENTRE AND MATERNITY ANNEXE", "7, KING-GEORGE V. ROAD, ONIKAN, LAGOS", "ETI-OSA"],
    ["BESTCARE HOSPITAL LIMITED", "2A, KEFFI STREET, SOUTHWEST, IKOYI, LAGOS", "ETI-OSA"],
    ["HEALING STRIPES HOSPITAL", "6B, HOUSE 3, PRINCE ALABA ONIRU WAY, ONIRU ROYAL ESTATE, VI, LAGOS", "ETI-OSA"],
    ["J RAPHA HOSPITAL", "40, ADDO LAMGBASA ROAD, BAKARE BUS STOP, AJAH, LAGOS", "ETI-OSA"],
    ["MAGNA CARTA HEALTH", "26B, KEFFI STREET, SOUTH WEST IKOYI, LAGOS", "ETI-OSA"],
    ["THE ROYAL INFIRMARY HOSPITAL", "BAKERY BUS/STOP, ALONG BADORE ADDO ROAD, AJAH", "ETI-OSA"],
    ["BADORE PRIMARY HEALTHCARE CENTRE", "BESIDE BADORE MODEL COLLEGE, ADDO/BADORE ROAD, ETI-OSA, Lagos", "ETI-OSA"],
    ["IKATE PRIMARY HEALTHCARE CENTRE", "5, IKATE ELEGUSHI ROAD", "ETI-OSA"],
    ["IKOYI PRIMARY HEALTHCARE CENTRE", "2, CARDINAL OLUBUNMI OKOJIE ROAD, IKOYI", "ETI-OSA"],
    ["ORIYANRIN PRIMARY HEALTHCARE CENTRE", "1-7, MURI OKUNOLA, VICTORIA ISLAND, IRU/VICTORIA ISLAND, LAGOS", "ETI-OSA"],
    ["IBEJU-LEKKI GENERAL HOSPITAL, AKODO", "KM 21, LAGOS ROAD, BEFORE LEKKI FREE TRADE ZONE, AKODO, IBEJU-LEKKI, LAGOS", "IBEJU-LEKKI"],
    ["DEE GOODNEWS HOSPITAL", "WHITE HOUSE BY LIVINGSTONE ESTATE, EPELEMEJE COMMUNITY, OROFUN TOWN, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["DESOL MEDICAL CENTRE", "12, BALOGUN ESTATE ROAD, OPP FARA PARK, ABIJO", "IBEJU-LEKKI"],
    ["FAMOUS HOSPITAL", "1, ALELU STREET, OPPOSITE LEKKI FREE TRADE ZONE, TIYE TOWN, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["GOFEE HOSPITAL LTD", "HOUSE 5, ROAD 2B, MARKET STREET, OFF OGUNFOYE PALACE ROAD, EPUTU, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["OCEANSIDE HOSPITAL", "15, ACHIEVERS COMMUNITY, ELEPETE, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["ST. ANGELA'S HOSPITAL", "IGBOJIA ROAD, SHAPATI, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["ST. NICHOLAS HOSPITAL CLINIC", "LEKKI FREE TRADE ZONE, 2ND GATE, IMOBIDO BUS-STOP, IBEJU-LEKKI", "IBEJU-LEKKI"],
    ["TRANSAQUATIC HOSPITAL", "KM 35, LEKKI-EPE EXPRESS WAY, OPP. TOYOTA AUTO NATION, BOGIJE, LAGOS", "IBEJU-LEKKI"],
    ["AWOYAYA PRIMARY HEALTHCARE CENTRE", "SANNI ELEKU STREET, AWOYAYA COMMUNITY TOWN, IBEJU LEKKI, Lagos", "IBEJU-LEKKI"],
    ["IBEJU PRIMARY HEALTHCARE CENTRE", "OPPOSITE SUBEB OFFICE, IBEJU LEKKI, LAGOS,", "IBEJU-LEKKI"],
    ["OKUNRAYE PRIMARY HEALTHCARE CENTER", "ALONG LEKKI EXPRESS ROAD, ELEKO JUNCTION, OKUNRAYE TOWN.", "IBEJU-LEKKI"],
    ["ORIMEDU PRIMARY HEALTHCARE CENTRE", "ORIMEDU COMMUNITY TOWN, IBEJU LEKKI, LAGOS", "IBEJU-LEKKI"],
    ["LEKKI PRIMARY HEALTHCARE CENTER", "1, AYEGBAMI QUARTERS, LEKKI.", "IBEJU-LEKKI"],
    ["GENERAL HOSPITAL, IFAKO-IJAIYE", "14, COLLEGE ROAD, OFF IJU ROAD, IFAKO-IJAIYE, LAGOS", "IFAKO-IJAIYE"],
    ["ANCILLA CATHOLIC HOSPITAL, IJU", "3/5 MUYIWA OLOJO STREET, IJU", "IFAKO-IJAIYE"],
    ["ANTHONY CARDINAL OKOGIE'S MEDICAL CENTER", "7, ADE-OMINUGA STREET, NEW OKO OBA, AGEGE", "IFAKO-IJAIYE"],
    ["AYODELE MEDICAL CENTRE", "1, AYODELE CLOSE, OFF JONATHAN COKER ROAD, FAGBA", "IFAKO-IJAIYE"],
    ["BISAM HOSPITAL", "612, LAGOS-ABEOKUTA EXPRESSWAY, IFAKO-IJAIYE, ,", "IFAKO-IJAIYE"],
    ["BLOOMING CARE HOSPITAL", "30, BAALE ANIMASHAUN ROAD, ALAKUKO, IFAKO-IJAIYE, LAGOS", "IFAKO-IJAIYE"],
    ["CAVESBURY HOSPITAL AND HEALTHCARE", "THE CAVESBURY PLACE, OFF ABRAHAM AFOLABI STREET, LAGOS-ABEOKUTA EXPRESSWAY, OJOKORO", "IFAKO-IJAIYE"],
    ["CHYGOR-COLE HOSPITAL LIMITED", "123, AGBE ROAD, , JIBOWU ESTATE, ABULE EGBA, LAGOS", "IFAKO-IJAIYE"],
    ["CLIMAXX HOSPITAL", "27, OWU STREET, MOSHALASHI BUS STOP, ALAGBADO", "IFAKO-IJAIYE"],
    ["GEO-MARIE HOSPITAL", "35, ADEPEGBA STREET, ABULE-EGBA, ALIMOSHO, LAGOS", "IFAKO-IJAIYE"],
    ["HANOVILLE SPECIALIST HOSPITAL & FERTILITY CENTRE", "14, IYERE OKOJIE CRESCENT, OFF OLOYEDE STREET, NDIKE BUS STOP, OBAWOLE, OGBA", "IFAKO-IJAIYE"],
    ["JEFIS SPECIALIST HOSPITAL", "9, ADEGBOLA STREET, OFF BAALE ANIMASHAUN ROAD, ALAKUKO, LAGOS", "IFAKO-IJAIYE"],
    ["LIFE-OASIS HEALTH HOSPITAL", "65, OYEMEKUN STREET, OFF COLLEGE ROAD, IFAKO-IJAIYE", "IFAKO-IJAIYE"],
    ["LONGE MEDICAL CENTRE", "126, OLUSEGUN OSOBA ROAD, OREMETA BUS-STOP, AGBADO", "IFAKO-IJAIYE"],
    ["LONGING MEDICAL CENTRE", "3-5, JOSEPHA CLOSE, OFF OGUNDEJI OGUNTONA STREET, AJALA BUS-STOP, IJAIYE-OJOKORO", "IFAKO-IJAIYE"],
    ["MACEDONIA SPECIALIST HOSPITAL", "28, IJAIYE ROAD, OGBA", "IFAKO-IJAIYE"],
    ["MASOL HOSPITAL CLINIC AND MATERNITY HOME", "8, MASOL HOSPITAL STREET, NEW OKO OBA, ABULE-EGBA", "IFAKO-IJAIYE"],
    ["OSUNTUYI MEDICAL CENTER, IJU", "225, IJU ROAD, IFAKO-IJAIYE", "IFAKO-IJAIYE"],
    ["OUR FRIEND HOSPITAL", "10, ADEPITAN STREET, OFF HARUNA STREET, HARUNA BUS STOP, COLLEGE ROAD, IFAKO-IJAIYE, LAGOS", "IFAKO-IJAIYE"],
    ["P & G MEDICAL CENTRE", "29, SANNI LABODE STREET, NEW OKO-OBA, ABULE-EGBA, LAGOS", "IFAKO-IJAIYE"],
    ["PACIFIC HOSPITAL", "4, SHOBEYOJO STREET, OFF IJU ROAD BY ELLIOT B/STOP, IFAKO-IJAIYE", "IFAKO-IJAIYE"],
    ["PRECIOUS GIFT MEDICALS", "81, ADENEKAN STREET, OFF ALAKUKO ROAD, ALIMOSHO", "IFAKO-IJAIYE"],
    ["REM YEMS HOSPITAL", "7, FATUNBI STREET, KOLLINGTON, ALAGBADO", "IFAKO-IJAIYE"],
    ["SAMOM MEDICAL CENTER", "5, ANUOLUWAPO STREET, IJAIYE, OJOKORO", "IFAKO-IJAIYE"],
    ["STANDARD LIFE CARE HOSPITAL", "6, ORENIWON STREET, ABULE-EGBA, OJOKORO, LAGOS", "IFAKO-IJAIYE"],
    ["ST CROST HOSPITAL", "208, IJU ROAD, GUDUGBA BUS STOP, ISHAGA", "IFAKO-IJAIYE"],
    ["ST THOMAS'S HOSPITAL", "17, AWONI-MURPHY STREET,  OFF HARUNA BUS STOP, IFAKO-IJAIYE, LAGOS", "IFAKO-IJAIYE"],
    ["AGBADO (KOLA) PRIMARY HEALTHCARE CENTRE", "NURENI YUSUF ROAD, KOLA BUSTOP, AGBADO", "IFAKO-IJAIYE"],
    ["IFAKO PRIMARY HEALTHCARE CENTER", "1, SANUSI AJILETE STREET, OFF COLLEGE ROAD, LAGOS, LAGOS", "IFAKO-IJAIYE"],
    ["LAGOS STATE UNIVERSITY TEACHING HOSPITAL", "1, OBA AKINJOBI ROAD, IKEJA, LAGOS", "IKEJA"],
    ["BODET MEDICARE AND MATERNITY CENTRE", "6, ODEWALE STREET, OFF KUDIRAT ABIOLA WAY, ALAUSA BUS STOP, IKEJA", "IKEJA"],
    ["COUNTY HOSPITAL LIMITED", "43/45, ISHERI ROAD, AGUDA, OGBA, LAGOS", "IKEJA"],
    ["DE VINE HOSPITAL", "8, LAWAL STREET, OREGUN, IKEJA, LAGOS", "IKEJA"],
    ["G & S MEDICAL AND DENTAL CLINICS", "15, MUIBI STREET, 1ST JUNCTION BUS-STOP, OKE-IRA ROAD, OGBA", "IKEJA"],
    ["J. A. LASHMAN HOSPITAL LTD", "28, SHOBOWALE STREET, OFF AKILO ROAD, OGBA", "IKEJA"],
    ["MOTAYO HOSPITAL", "3, OWODUNNI STREET, OFF TOYIN STREET, IKEJA, LAGOS", "IKEJA"],
    ["POLICE COLLEGE HOSPITAL", "POLICE COLLEGE, GRA, IKEJA", "IKEJA"],
    ["ST MARY'S SPECIALIST HOSPITAL", "PLOT 458, TITILAYO ADEDOYIN STREET, OMOLE PHASE 1, IKEJA, LAGOS", "IKEJA"],
    ["ONILEKERE PRIMARY HEALTHCARE CENTRE", "11, OGUNSULU STREET, CEMENT BUS STOP, IKEJA, Lagos", "IKEJA"],
    ["OREGUN PRIMARY HEALTHCARE CENTRE", "KUDIRAT ABIOLA WAY, OREGUN, IKEJA, Lagos", "IKEJA"],
    ["GENERAL HOSPITAL, IJEDE", "PALACE ROAD, BESIDE EGBIN POWER PLC, IKORODU, LAGOS", "IKORODU"],
    ["GENERAL HOSPITAL, IMOTA", "IMOTA, IKORODU", "IKORODU"],
    ["IKORODU GENERAL HOSPITAL", "TOS BENSON ROAD, IKORODU, LAGOS", "IKORODU"],
    ["ALHERI HOSPITAL", "60, AGUNFOYE ROAD, AKANUN ADAMO BUS STOP, IKORODU", "IKORODU"],
    ["AMODU ADESOLA MEMORIAL HOSPITAL", "5, ANIBABA STREET, IKORODU", "IKORODU"],
    ["ARUNA OGUN MEMORIAL SPECIALIST HOSPITAL", "2/4, BAMIMOSU STREET, EBUTE, IKORODU, LAGOS", "IKORODU"],
    ["BELLADIO MEDICAL CENTER", "23, UNITY ESTATE {NOW DIAMOND ESTATE}, BY YAH LATEEF STREET, IYANA ODO AGURA, GBERIGBE, IKORODU", "IKORODU"],
    ["BERNICE CLINIC", "318, LAGOS ROAD, OGOLONTO BUS-STOP, BESIDE BRT BRIDGE, OGOLONTO, IKORODU", "IKORODU"],
    ["BOLAKUNMI IDOWU MEMORIAL MEDICAL CENTRE", "5, SEGUN ISHOLA STREET, IKORODU WEST, LAGOS", "IKORODU"],
    ["CROWN CONSULT HOSPITAL", "4, RUFUS CRESECENT, OFF AMUSA STREET, IJEDE ROAD, IKORODU", "IKORODU"],
    ["CUTE HEALTHCARE LTD", "190, IRE ROAD, IRE AGUNFOYE, IGBOGBO, IKORODU", "IKORODU"],
    ["DASOCHRIS HOSPITAL", "2ND AVENUE, PABOYEJO ESTATE, BEHIND HOSANNA CHAPEL ALONG ODONLA, ODOGUNYAN", "IKORODU"],
    ["DAUGHTERS OF CHARITY OF ST VINCENT DE PAUL", "56, RENECON ROAD,  MACAULAY JUNCTION, BAYEKU, IGBOGBO, IKORODU", "IKORODU"],
    ["DELE HOSPITAL", "15, AJASA LAMBERU STREET, OFF OBAFEMI AWOLOWO ROAD,OKE OTA-ONA, IKORODU", "IKORODU"],
    ["DE DUNAMIS HOSPITAL LTD", "NO 1, OSHO ALAGBA OREMU STREET, OLU-ODO, IGBOGBO", "IKORODU"],
    ["EBUNOLUWA HOSPITAL", "11, GBASEMO STREET, AGAA, IKORODU", "IKORODU"],
    ["ESSO HOSPITAL", "ITELE AGBAKU ROAD, MAYA, IKORODU, LAGOS", "IKORODU"],
    ["EVOLUTION HOSPITALS LTD", "16-18, FALILAT OJOLOWO STREET, CPI BUS STOP, GBERIGBE, IKORODU", "IKORODU"],
    ["EXCEEDING GRACE HOSPITAL", "14, FRANCIS ADEGBOYEGA STREET, AGBEDE, IKORODU, LAGOS", "IKORODU"],
    ["FIRST CROSS NURSING HOME", "3, OLUSOLA OYEBODE AVENUE, OFF IGBE ROAD, OREYO, IGBOGBO, IKORODU", "IKORODU"],
    ["FRAMAG HOSPITAL", "25, GIWA IMALE STREET, BUTTERFLY ISLAND, AGRIC, IKORODU", "IKORODU"],
    ["G-KAMZA MEDICAL CENTER", "4, FELIX MAJAYI STREET, OWODE IBESHE, IKORODU, LAGOS", "IKORODU"],
    ["GOOD SHEPHERD CATHOLIC HOSPITAL", "17/19, SALVATION STREET, IRAWO, AJEGUNLE", "IKORODU"],
    ["IMHENRION HOSPITAL", "2, JOSADE WAY, AGUNFOYE, ADAMO, IKORODU", "IKORODU"],
    ["JOBI CLINIC AND MATERNITY HOSPITAL LTD", "3/5 ADEYERI OWUYI STREET, IKORODU, LAGOS", "IKORODU"],
    ["KOLAK HOSPITAL", "158, SAGAMU ROAD, OPPOSITE LASUSTECH FIRST GATE, IKORODU", "IKORODU"],
    ["LIFESOURCE HOSPITAL", "9, CHURCHILL EMENIKE STREET, CRYSTAL ESTATE, OFF MOWO-NLA ROAD, JAJO, IJEDE", "IKORODU"],
    ["OPELOYERU CLINIC & HOSPITAL LTD", "ITELE DIGBALOYE, COUNSELOR BUS STOP, ADJACENT OPELOYERU MOSQUE, MAYA", "IKORODU"],
    ["PALMVILLE MEDICAL CENTRE", "10, MULIKAT ONISOWO STREET, IGBO OLUWO ESTATE, JUMOFAK BUS-STOP, IKORODU", "IKORODU"],
    ["PRIESTHOOD HOSPITAL", "1, POIKI JUNCTION, LAJO, IKORODU", "IKORODU"],
    ["RAPHA MEDICAL CENTRE", "14, MUYIDEEN STREET, IKORODU CENTRAL, IKORODU, LAGOS", "IKORODU"],
    ["ROCK OF LIFE HOSPITAL", "9, AKINYEMI BALOGUN STREET, LUCKY FIBER, IKORODU", "IKORODU"],
    ["SHANU MEDICAL CENTRE", "8, OKE STREET, OKE-RIYA, IKORODU", "IKORODU"],
    ["SHOLA MEDICAL CENTER", "108, OBA OMOLAJA OGUNLEWE ROAD, IGBOGBO, IKORODU", "IKORODU"],
    ["SILVER CREST HOSPITAL", "187, ISAWO ROAD, OWOSENI BUS STOP, AGRIC, IKORODU", "IKORODU"],
    ["STEVANS HOSPITAL", "17, ORI-OKUTA ROAD, OFF ISAWO ROAD, OKIKI BUS STOP, AGRIC", "IKORODU"],
    ["ST RAPHAEL DIVINE MERCY SPECIALIST HOSPITAL", "BOJE TOWN, IJEDE ROAD, IKORODU, LAGOS", "IKORODU"],
    ["THE EXCELLENCE HOSPITAL", "5, ALOGBA STREET, OFF NIBESHE ROAD, EBUTE, IKORODU", "IKORODU"],
    ["AGBEDE PRIMARY HEALTHCARE CENTRE", "AGBEDE ROAD, AGBEDE, IKORODU", "IKORODU"],
    ["IGBOGBO PRIMARY HEALTHCARE CENTRE", "AGBELE ROAD, IKORODU", "IKORODU"],
    ["IMOTA PRIMARY HEALTHCARE CENTRE", "EBUTE AJEBO ROAD, ATERE WARD, IMOTA, LAGOS", "IKORODU"],
    ["ODONLA PRIMARY HEALTHCARE CENTRE", "ODONLA WAY, ODOGUNYAN, IKORODU, Lagos", "IKORODU"],
    ["OKE-ELETU PRIMARY HEALTHCARE CENTRE", "IJEDE ROAD, HEALTH CENTER BUS-STOP, OKE-ELETU, IJEDE", "IKORODU"],
    ["IPAKODO PRIMARY HEALTHCARE CENTER", "1, IPEBI CLOSE, EBUTE, LAGOS", "IKORODU"],
    ["ITA ELEWA PRIMARY HEALTHCARE CENTRE", "3, ORIWU ROAD, IKORODU", "IKORODU"],
    ["GBAGADA GENERAL HOSPITAL", "1, HOSPITAL ROAD, GBAGADA, LAGOS", "KOSOFE"],
    ["AL-SADIQ MEMORIAL HOSPITAL", "21, AYISAT STREET, OFF AGILITI ROAD, BEHIND MILE 12 MARKET LAGOS", "KOSOFE"],
    ["APEX-CARE HOSPITALS", "42/44 KUJORE STREET, OJOTA, KOSOFE, LAGOS", "KOSOFE"],
    ["AZIR HEALTHCARE", "47, ODUNTAN STREET, KETU, KOSOFE, LAGOS", "KOSOFE"],
    ["BARBINTON MEDICAL CENTRE", "9, ANIBABA STREET, IYANA SCHOLL BUS STOP, KETU", "KOSOFE"],
    ["BASE SPECIALIST HOSPITAL", "22, DEMUREN ROAD, KETU-ALAPERE, LAGOS", "KOSOFE"],
    ["BERNICE CLINIC", "5, FADARE STREET, MILE 12, LAGOS", "KOSOFE"],
    ["DONAS SPECIALIST HOSPITAL", "62, OWULADE AVENUE, IRAWO BUS STOP, OWODE-ONIRIN, IKORODU", "KOSOFE"],
    ["FIRST CROSS NURSING HOME", "568, IKORODU ROAD, KETU", "KOSOFE"],
    ["FOLABI MEDICAL CENTRE", "78, OWORO ROAD, L & K BUS STOP, KOSOFE, LAGOS", "KOSOFE"],
    ["GIFTED HANDS MEDICAL CENTER", "25, OLD OLOWORA ROAD, ISHERI, MAGODO", "KOSOFE"],
    ["GLORIA HOSPITAL LTD", "9, OLADEINDE STREET, ANTHONY VILLAGE, LAGOS, LAGOS", "KOSOFE"],
    ["HAYY'S HAVEN HOSPITAL", "18, OLATUNJI LADIPO STREET, OFF CMD ROAD, IKOSI-MAGODO", "KOSOFE"],
    ["LADE HOSPITAL", "17, OLATUNJI IGE STREET, IKOSI-KETU, LAGOS", "KOSOFE"],
    ["MED-IN SPECIALIST HOSPITAL", "1/3 OSGBO STREET, OGUDU, OJOTA, LAGOS", "KOSOFE"],
    ["ST. NICHOLAS HOSPITAL, MARYLAND", "18, FARAMOBI AJIKE CRESCENT, OFF IKORODU ROAD, LAGOS", "KOSOFE"],
    ["THEO HOSPITAL LIMITED", "25, DAVIES STREET, KETU, KETU, LAGOS", "KOSOFE"],
    ["KETU PRIMARY HEALTHCARE CENTRE", "MASCARA AKINOLU STREET, OFF DEMURIN STREET, AGBOYI-KETU, LAGOS", "KOSOFE"],
    ["OGUDU PRIMARY HEALTHCARE CENTRE", "OGUDU ROAD, OGUDU, LAGOS", "KOSOFE"],
    ["BLAJE MUSTAPHA HOSPITAL (B.M.H)", "FORESYTHE STREET, LAFIAJI, LAGOS ISLAND, LAGOS", "LAGOS ISLAND"],
    ["DR ABIMBOLA AWOLIYI MEMORIAL HOSPITAL", "103, BAMGBOSE STREET, , LAGOS-EAST, LAGOS", "LAGOS ISLAND"],
    ["ST. NICHOLAS HOSPITAL", "57, CAMPBELL STREET, LAGOS ISLAND, LAGOS ISLAND , LAGOS", "LAGOS ISLAND"],
    ["THE HEALTH ARENA SPECIALIST CLINICS HOSPITAL & MATERNITY HOME", "12B, STRACHAN STREET, ORLANDO MARTINS, LAGOS ISLAND EAST, LAGOS", "LAGOS ISLAND"],
    ["IGA-IDUGANRAN PRIMARY HEALTHCARE CENTRE", "IGA-IDUGANRAN STREET, ADENIJI ADELE ROAD, LAGOS ISLAND", "LAGOS ISLAND"],
    ["OBA ADEYINKA OYEKAN PRIMARY HEALTHCARE CENTRE", "ADENIJI ADELE ROUND ABOUT INSIDE BOLA TINUBU MULTI-PURPOSE CENTRE, LAGOS ISLAND", "LAGOS ISLAND"],
    ["OLOWOGBOWO PRIMARY HEALTHCARE CENTRE", "ELEGBATA STREET, LAGOS ISLAND", "LAGOS ISLAND"],
    ["SURA PRIMARY HEALTHCARE CENTRE", "1, SIMPSON STREET, SURA JUNCTION.", "LAGOS ISLAND"],
    ["EBUTE-METTA COMPREHENSIVE HEALTH CENTRE", "103-116 CEMETRY STREET, EBUTE-METTA, LAGOS", "LAGOS MAINLAND"],
    ["HARVEY ROAD HEALTH CENTRE & MATERNITY", "8, HARVEY ROAD, YABA, LAGOS", "LAGOS MAINLAND"],
    ["BRICKFIELD MEDICAL CENTRE", "15, ADEMUYIWA STREET, COSTAIN OFF APAPA ROAD,  EBUTE-METTA, LAGOS", "LAGOS MAINLAND"],
    ["COTTAGE MEDICARE HOSPITAL", "18, IWAYA ROAD, ONIKE, YABA, LAGOS", "LAGOS MAINLAND"],
    ["FEDERAL MEDICAL CENTER, EBUTE-METTA", "RAILWAY COMPOUND, EBUTE-METTA, LAGOS", "LAGOS MAINLAND"],
    ["MARIEN HOSPITAL LTD", "7, MONTGOMERY ROAD, YABA, LAGOS MAINLAND, LAGOS", "LAGOS MAINLAND"],
    ["AYETORO PRIMARY HEALTHCARE CENTER", "1, WRIGHT STREET, UNDER OKOBABA OVERHEAD BRIDGE, ADEKUNLE, YABA", "LAGOS MAINLAND"],
    ["IWAYA PRIMARY HEALTHCARE CENTRE", "25/27 OMOTOLA STR, IWAYA, YABA", "LAGOS MAINLAND"],
    ["OTUMARA PRIMARY HEALTHCARE CENTRE", "15, AROWOJOLU STREET, ILAJE, EBUTE METTA, LAGOS", "LAGOS MAINLAND"],
    ["SIMPSON PRIMARY HEALTHCARE CENTRE", "2 SIMPSON STREET,  EBUTE METTA,  LAGOS", "LAGOS MAINLAND"],
    ["MUSHIN GENERAL HOSPITAL", "48, OLIYIDE STREET, MUSHIN, LAGOS", "MUSHIN"],
    ["FAFOLU MEDICAL CENTER", "22, FAFOLU STREET, MUSHIN", "MUSHIN"],
    ["FIRST HERITAGE MEDICARE SERVICES LTD", "29/33, AYANTUGA STREET, OLORUNSOGO, MUSHIN", "MUSHIN"],
    ["HILLSTAR CLINICS (NIG) LTD", "98, PALM AVENUE, MUSHIN, LAGOS", "MUSHIN"],
    ["IYALODE BISOYE TEJUOSO HOSPITAL", "20/22, ILUPEJU BY-PASS, ILUPEJU, LAGOS", "MUSHIN"],
    ["MAZAF MEDICAL CENTER", "8, MACAULAY STREET, OLORUNSOGO, MUSHIN", "MUSHIN"],
    ["NUSAMIN CLINIC AND HOSPITAL LIMITED", "34, APENA STREET, MUSHIN", "MUSHIN"],
    ["SILOAN MEDICAL CENTER, MUSHIN", "68, AKANRO STREET, ILASAMAJA, MUSHIN", "MUSHIN"],
    ["AJEABO PRIMARY HEALTHCARE CENTRE", "56, OGUNAIKE ST,INSIDE AJEABO PRY SCH, AJEABO, ILASA", "MUSHIN"],
    ["AYANTUGA PRIMARY HEALTHCARE CENTRE", "49, AYANTUGA STREET, MUSHIN", "MUSHIN"],
    ["PALM AVENUE PRIMARY HEALTHCARE CENTER", "PALM AVENUE, MUSHIN, LAGOS", "MUSHIN"],
    ["COKER PRIMARY HEALTHCARE CENTRE", "26, COKER ROAD, ILUPEJU", "MUSHIN"],
    ["ADEMOLA HOSPITAL AND MATERNITY LIMITED", "1, OMOWALE STREET, KM 28, LAGOS BADAGRY EXPRESSWAY, IJANIKIN, LAGOS", "OJO"],
    ["CARES AND CARES HOSPITAL", "1B OLUBIYI STREET, ALONG GREAT CHALLENGE ROAD, IYANA SCHOOL BY 2ND TRANSFORMER BUS STOP, UNITY ESTATE, IBA", "OJO"],
    ["FEMOLA HOSPITAL & CLINICS", "106, OLOTO RING ROAD, IJANIKIN, LAGOS", "OJO"],
    ["GODCURES HOSPITAL", "19, ERA ROAD, ILOGBO-AJANGBADI, AJANGBADI, LAGOS", "OJO"],
    ["GOODNESS MEDICAL CENTRE", "151, SHIBIRI ROAD, OPP. OTTO-AWORI DEVELOPMENT COUNCIL, OJO, LAGOS", "OJO"],
    ["HEALING LAND HOSPITAL", "106, OKE-AGBO ROAD, OKE-AGBO, OJO", "OJO"],
    ["ILOGBO CENTRAL HOSPITAL", "175, ILOGBO ROAD,, ALABA INTERNATIONAL MARKET AREA, LAGOS, AJANGBADI, LAGOS", "OJO"],
    ["KILADEJO HOSPITAL AND SPECIALIST CLINICS", "15, PPL ROAD, OFF BADAGRY EXPRESSWAY, OKOKOMAIKO, OJO, LAGOS", "OJO"],
    ["TREASURE HOSPITAL", "7, ARIYO CLOSE, IBA", "OJO"],
    ["TRINITY ROCK HOSPITAL AND MATERNITY", "35, IGBO-ELERIN STREET, IGBO-ELERIN, OKOKOMAIKO", "OJO"],
    ["OJO PRIMARY HEALTHCARE CENTER", "REST HOUSE ROAD, BESIDE TOWN HALL, OJO", "OJO"],
    ["IJANIKIN PRIMARY HEALTHCARE CENTRE", "KM 28, LAGOS BADAGRY EXPRESSWAY, ILE OBA BUS STOP, IJANIKIN", "OJO"],
    ["ISOLO GENERAL HOSPITAL", "121, MUSHIN ROAD, ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["AGO MEDICAL CENTER", "13, OYINLOLA CLOSE, OFF AGO PALACE WAY, OKOTA, LAGOS", "OSHODI-ISOLO"],
    ["BOSE SPECIALIST HOSPITAL", "7, ILORI STREET, IRE-AKARI ESTATE, ISOLO", "OSHODI-ISOLO"],
    ["BOSUN HOSPITAL AND MATERNITY HOME", "5, KAZEEM STREET, OFF DALEKO BUS STOP, EJIGBO", "OSHODI-ISOLO"],
    ["DIALYZER MEDICAL CENTRE", "60, AROWOJOBE STREET, OSENI BUS STOP, OSHODI, LAGOS", "OSHODI-ISOLO"],
    ["DIVINE GRACE HEALING STRIPES HOSPITAL", "3, SHOBOGUN ROFA STREET, MAFOLUKU, OSHODI, LAGOS", "OSHODI-ISOLO"],
    ["DOLU HOSPITAL", "7, SUNMOLA ABAYOMI STREET, MAFOLUKU, OSHODI-ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["EDMAC MEDICAL CENTRE", "31, AYODELE STREET, MAFOLUKU, OSHODI", "OSHODI-ISOLO"],
    ["GEO MEDICAL CENTRE", "12, SUBAIRU STREET, LADIPO, SHOGUNLE, LAGOS", "OSHODI-ISOLO"],
    ["HEALING TOUCH HOSPITAL", "42, OLUDEGUN AVENUE, IRE AKARI ESTATE, ISOLO", "OSHODI-ISOLO"],
    ["HOUSE OF JULIUS HOSPITAL", "57, MURITALA MUHAMMAD INTERNATIONAL AIRPORT ROAD, AJAO ESTATE,, ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["ISOLO ESTATE CLINIC", "GREEN STREET, JAKANDE ESTATE, OSHODI-ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["JERICHO HOSPITAL", "37A, AYODELE STREET, MAFOLUKU, OSHODI", "OSHODI-ISOLO"],
    ["LONGLIFE HOSPITAL", "22, OWOSENI STREET, OSHODI", "OSHODI-ISOLO"],
    ["MEDIBAM SPECIALIST HOSPITAL", "8, JUBRIL OLABISI STREET, OFF IDIMU ROAD, EJIGBO, LAGOS", "OSHODI-ISOLO"],
    ["ONELIFE HOSPITAL", "485, AGEGE MOTOR ROAD, BOLADE-OSHODI, OSHODI-ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["PETROS FOUNDATION CLINICS", "20, SEINDE CALISTO CRESCENT, CHARITY BUS-STOP, OSHODI", "OSHODI-ISOLO"],
    ["PINECREST SPECIALIST HOSPITAL", "83, MAKINDE STREET, MAFOLUKU, OSHODI, LAGOS", "OSHODI-ISOLO"],
    ["RIVET SPECIALIST HOSPITAL", "22, ADEJUMO TENNIS CLUB ROAD, ILAMOSE, OKE-AFA, LAGOS", "OSHODI-ISOLO"],
    ["SENTINEL HOSPITAL", "1, BENSON AKINYELE STREET, OKE-AFA, ISOLO", "OSHODI-ISOLO"],
    ["SILOAN MEDICAL CENTER, EJIGBO", "3, MOHAMMED AKIJE STREET, EJIGBO", "OSHODI-ISOLO"],
    ["ST. CATHERINE OF SIENA MEDICAL CENTRE", "45/49 OLD EWU ROAD, MAFOLUKU, OSHODI", "OSHODI-ISOLO"],
    ["ST. EMMANUEL HOSPITAL", "2, BOLA ADEMUYIWA STREET, OFF OSOLO WAY, ISOLO, LAGOS", "OSHODI-ISOLO"],
    ["ST. RAPHAEL HOSPITAL LTD", "114, LATEEF ADEGBOYEGA STREET, OFF AGO PALACE WAY, OKOTA", "OSHODI-ISOLO"],
    ["UNIQUE CARE HOSPITAL, CLINIC & MATERNITY", "53, TEMITOPE STREET, ILASAMAJA, LAGOS", "OSHODI-ISOLO"],
    ["WATERFALLS HOSPITAL & MATERNITY, OKOTA", "112, OKOTA ROAD, OKOTA ROUNDABOUT, OKOTA", "OSHODI-ISOLO"],
    ["WESTCARE HOSPITAL-EJIGBO", "31, IFOSHI ROAD, PIPELINE BUS STOP, OPPOSITE CHRISLAN MOSQUE, ORILOWO AREA,  EJIGBO, LAGOS", "OSHODI-ISOLO"],
    ["ILASA PRIMARY HEALTHCARE CENTER", "32, OGUNBOWALE STREET, ILASA, ISOLO", "OSHODI-ISOLO"],
    ["ISHAGA PRIMARY HEALTHCARE CENTRE", "UGALI STREET, CLOSE TO ISHAGA  POLICE STATION", "OSHODI-ISOLO"],
    ["MAFOLUKU PRIMARY HEALTHCARE CENTRE", "2, AJIBULU STREET, MAFOLUKU, OSHODI", "OSHODI-ISOLO"],
    ["OSHODI PRIMARY HEALTHCARE CENTRE", "4, OGUNLANA STREET, OSHODI, LAGOS", "OSHODI-ISOLO"],
    ["GENERAL HOSPITAL, SOMOLU", "1, OGUNTOLU STREET, SOMOLU, LAGOS", "SHOMOLU"],
    ["ADEYIPE MEDICAL CENTRE", "81, IGI OLUGBIN STREET, MATERNITY BUS STOP, BARIGA", "SHOMOLU"],
    ["ANIYUN HOSPITALS LIMITED", "3, FEMI ADERIBIGBE CLOSE OFF DIYA STREET, IFAKO, GBAGADA", "SHOMOLU"],
    ["LADI LAK MEDICAL CENTRE", "53, IGI OLUGBIN STREET,  LADI LAK, BARIGA, LAGOS", "SHOMOLU"],
    ["MARY ADE SPECIALIST HOSPITAL", "PLOT 24, SHITTU ANIMASHAUN STREET, OFF JAGUNONI STREET, OFF LANRE AWOLOKUN ROAD, GBAGADA PHASE 2.", "SHOMOLU"],
    ["MICEL HOSPITAL", "4, BROWN STREET, SHOLUYI, GBAGADA", "SHOMOLU"],
    ["OSUNTUYI MEDICAL CENTER, OBANIKORO", "9, ALHAJI SALISU STREET, OBANIKORO", "SHOMOLU"],
    ["TOLA CRESCENT MEDICAL CENTER", "94, ST FINBARR'S COLLEGE ROAD, SHOMOLU, LAGOS", "SHOMOLU"],
    ["AKOKA PRIMARY HEALTHCARE CENTRE", "31/33, IBUKUNOLU STREET, AKOKA, LAGOS", "SHOMOLU"],
    ["CMS PRIMARY HEALTHCARE CENTRE", "DEJI ALADEJOBI STREET ILAJE BUS-STOP BARIGA.", "SHOMOLU"],
    ["ASIWAJU BOLA AHMED TINUBU COMPREHENSIVE HEALTH CENTER (ABAT)", "ALABA ORO, OFF COKER-ORILE ROAD, IFELODUN LCDA, ORILE", "SURULERE"],
    ["RANDLE GENERAL HOSPITAL", "68, RANDLE AVENUE, SURULERE, LAGOS", "SURULERE"],
    ["ABLEGOD HOSPITAL", "52, IJESHA ROAD, SURULERE", "SURULERE"],
    ["FESOCK SPECIALIST CLINICS AND MATERNITY", "12, ALHAJI OLAKUNLE STREET, OFF OMILANI STREET, IJESHATEDO, SURULERE", "SURULERE"],
    ["FIRST CROSS HOSPITAL", "2, OSHOFISAN STREET, ITIRE, SURULERE", "SURULERE"],
    ["FIRST FAITH MEDICAL CENTRE LTD", "5, KARIMU STREET, COKER, ORILE-IGANMU, LAGOS", "SURULERE"],
    ["HIS MERCY HOSPITAL AND MATERNITY HOME", "17, ADEYEMI STREET, ORILE IGANMU, LAGOS", "SURULERE"],
    ["HIS STRIPES SPECIALIST HOSPITAL", "19, SAVAGE STREET, ORILE IGANMU , SURULERE, LAGOS", "SURULERE"],
    ["ISIOMA HOSPITAL", "28, MOLUSI AVENUE, IKATE, SURULERE", "SURULERE"],
    ["JALUPON SPECIALIST CLINICS", "63, BODE THOMAS STREET, SURULERE", "SURULERE"],
    ["JOEDAN HOSPITAL LTD", "3, LAGOS BADAGRY EXPRESS ROAD, ORILE-IGANMU, SURULERE, LAGOS", "SURULERE"],
    ["MERCY THOMAS OREDUGBA MEDICAL & DENTAL CENTRE", "8, MOGAJI STREET, IJESATEDO OFF PAKO AGUDA, ITIRE-IKATE LCDA, LAGOS", "SURULERE"],
    ["OLA-IYA SPECIALIST HOSPITAL AND MATERNITY", "29, AKINHANMI STREET, BY ANGLICAN GIRLS GRAMMAR SCHOOL, OFF FASHORO STREET, SURULERE, LAGOS", "SURULERE"],
    ["OLANIBA MEMORIAL SPECIALIST HOSPITAL", "10A OLATUNDE ONIMOLE STREET, AGUDA, SURULERE, LAGOS", "SURULERE"],
    ["PRIMUS HOSPITALS LTD", "272, IJESHA ROAD, IJESHATEDO, SURULERE", "SURULERE"],
    ["SIKEOYE HOPE CLINIC", "79, KARIMU STREET, SURULERE, LAGOS", "SURULERE"],
    ["ST. NICHOLAS HOSPITAL, SURULERE", "1, JAMES ROBERTSON ROAD, SURULERE, LAGOS", "SURULERE"],
    ["ST. LUKE'S MEDICAL CENTER", "1, ADEDOYIN STREET, OFF OMILANI STREET, IJESHATEDO, SURULERE", "SURULERE"],
    ["TOPTEE MEDICAL CENTER", "40, OGUNLANA DRIVE, OFF LAWANSON ROAD, SURULERE", "SURULERE"],
    ["AKERELE PRIMARY HEALTHCARE CENTER", "35A, AKERELE STREET, SURULERE", "SURULERE"],
    ["COKER AGUDA PRIMARY HEALTHCARE CENTRE", "19, THOMAS ANIMASHAUN STREET, COKER AGUDA , SURULERE, LAGOS", "SURULERE"],
    ["EJIRE PRIMARY HEALTHCARE CENTRE", "34, EJIRE STR, OFF OREDOLA/KARONWI STR, IJESHA", "SURULERE"],
  ];

  const table2Data = [
    ["Abek Pharmacy", "143, Ipaja Road by Agbotikuyo B/Stop, Agege, Lagos", "AGEGE", "AGEGE", "08037863511"],
    ["Caratiyah Pharmacy", "90, Dopemu Road, Alhaja Shifau Bus Stop, Dopemu Agege, Lagos", "AGEGE", "AGEGE", "08027288555"],
    ["Medspring Pharmacy", "107, Old Ota Road, Oke Odo, Off Ekoro, Abule Egba, Lagos", "AGEGE", "AGBADO-OKE ODO", "08091071350"],
    ["360 Degre Pharmacy (Agege)", "1 Capito Road Agege, Lagos", "AGEGE", "AGEGE", "08034980104"],
    ["Cassia Pharmacy", "No 300A Old Abeokuta road, by Church busstop (St Cyprain Catholic Church, by Da Silva estate, by Abimbola estate/NNPC fueling station, between Abbatoir and AbuleEgba flyover), Oko- Oba, Agege, Lagos", "AGEGE", "ORILE AGEGE", "08037870936"],
    ["Denrobe Pharmacy", "50, Okito street, awodi-ora, Ajeromi-ifelodun, Apapa, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08033420140"],
    ["Emmacity Pharmacy", "8, Baale Street, Ajegunle, Apapa, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08183469146"],
    ["Jogen Pharmacy", "26, Ojo road, Ajegunle, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08123485767"],
    ["Kaodaf Pharmacy", "7, Wilmer Crescent by Coca Cola Depot, Olodi Apapa, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08098987200"],
    ["Zestcare Pharmacy", "74, Bale Street, Greenland Bus stop, Olodi-Apapa, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08023087506"],
    ["Marbido Pharmacy", "210 Idewu street, Oloidi Apapa, Lagos", "AJEROMI IFELODUN", "AJEROMI IFELODUN", "08033948277"],
    ["Bolutife Pharmacy", "60, Amusa Idowu Street, Ijegun, Ikotun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08037167414"],
    ["Bydow Pharmacy (Egbeda)", "60, Egbeda/Idimu rd, Egbeda (Jendor supermarket), Lagos.,", "ALIMOSHO", "EGBE IDIMU", "08088925278, 08096937417"],
    ["Bydow Pharmacy (Igando)", "19, Isheri LASU road, Isheri-Igando, Jendol Superstore, Lagos.,", "ALIMOSHO", "IGANDO IKOTUN", "07088925278, 07033626701"],
    ["Deken Place Pharmacy", "9A, Ajasa Command Road, Meiran, Lagos", "ALIMOSHO", "AGBADO-OKE ODO", "07067577005"],
    ["Fadob Pharmacy (Alagbado)", "24, Ikola Road, Church bustop, Alaso, Alagbado, Lagos.,", "ALIMOSHO", "AGBADO-OKE ODO", "08032345398, 08075993921"],
    ["Fadob Pharmacy (Ipaja)", "29, Salami Kasumi street, OPC junction, Mosan, Ipaja, Lagos.,", "ALIMOSHO", "MOSAN OKUNOLA", "08032345398, 08075993913"],
    ["Fadob Pharmacy (Iyana- Ipaja)", "2, Bola Dada Street, Hilltop Estate Gate, Aboru, Iyana Ipaja, Lagos.,", "ALIMOSHO", "AGBADO-OKE ODO", "08032345398, 08075993904"],
    ["Jaybee Pharmacy", "65, Idimu Road, College Bus Stop, Ikotun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08023629368"],
    ["Latol Pharmacy (Ijegun- Ikotun)", "322, Ijegun Road, Obalagbe B/Stop, Opp Conoil Filling Station, Ikotun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "080357777487"],
    ["Latol Pharmacy (Onilewura- Egbe)", "23, Onilewura Street, Off Liasu Road, Ile Iwe Bus stop, synagogue road, Egbe, Ikotun, Lagos", "ALIMOSHO", "EGBE IDIMU", "08086631319"],
    ["Mebina Pharmacy", "KM 10 LASU-Isheri Road, Akesan Bus stop, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08069190409"],
    ["Nectarite Pharmacy", "2 Olorunwa close, karimu laka street, adjacent to the new oba's palace, Egbeda, Lagos", "ALIMOSHO", "ALIMOSHO", "08175800735"],
    ["Newton Pharmacy (Akesan)", "Prime Mart Superstores, Vulcanizer Bus stop, Akesan, Off LASU-idimu iba Express way, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "09034070567"],
    ["Richprest Pharmacy", "21, Afolabi Street, ege, Egbe-Idimu LCDA, Lagos", "ALIMOSHO", "EGBE IDIMU", "08052371894"],
    ["Riyi Pharmacy (Igando)", "2, Christ the King street, Off Aribisala Street, Iya Gbogbo Bus stop, Agric road, Igando, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08023996688"],
    ["Riyi Pharmacy (Ikotun)", "35, El-bethel Church Street, Lawal Bus stop, Governor's road, Ikotun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08120466708"],
    ["Turmeric Pharmacy (Isheri oshun)", "43, Isolo Road, Isheri Oshun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "09056206359"],
    ["Pricepoint Pharmacy", "28, Ekoro Road Abulegba Bus Stop Abulegba, Lagos", "ALIMOSHO", "AYOBO IPAJA", "08097474051"],
    ["Welnex Pharmacy (Ijegun)", "85, Isheri-Oshun Road, Ijegun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "07048437827"],
    ["Welnex Pharmacy (Ijeododo)", "1, Welnex Street, Ijeododo, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "07032112589"],
    ["Kerion pharmacy", "3rd Avenue, Opp., St Bernedette School Gowon Estate, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08177778913"],
    ["Massey Vickers Pharmacy (Egbeda 1)", "117, Egbeda Idimu Road, Abule Odu Bus stop, Egbeda, Lagos", "ALIMOSHO", "EGBE IDIMU", "08034683774"],
    ["Massey Vickers Pharmacy (Egbeda 2)", "214, Egbeda-Idimu Road, Car Wash Bus stop, Egbeda, Lagos", "ALIMOSHO", "EGBE IDIMU", "07015467122"],
    ["Massey Vickers Pharmacy (Ijegun)", "Ijegun, Twinsfaja Mall, Bank Bus stop, Ijegun Road, Ijegun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08033253463"],
    ["Massey Vickers Pharmacy (Obadore)", "10, Liasu Isheri Road, Obadore Bus stop, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "07017023246"],
    ["Kardinal Pharmacy", "134, Ijegun road, Ikotun, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08185156276"],
    ["Kent Pharmacy", "KM 2, Isheri-LASU Road, Odo Eran B/stop, RIK Event center building, Lagos", "ALIMOSHO", "IGANDO IKOTUN", "08023145073"],
    ["Uclich Pharmacy", "No. 3, Gordilove Street, off Vulcaniser Bus Stop, Akowonjo, Lagos", "ALIMOSHO", "ALIMOSHO", "08033224562, 08077077872"],
    ["Jodag Pharmacy", "Block 61, plot 1456, Leye Adebowale street, Heritage estate, Aboru, Alimosho, Lagos state.,", "ALIMOSHO", "AGBADO-OKE ODO", "08138257418, 08027827478"],
    ["Mascot Pharmacy", "1, Monilari Close by Church street, Shagari Estate, Akinogun, Ipaja, Lagos", "ALIMOSHO", "AYOBO IPAJA", "08026108324"],
    ["Quickmedics Pharmacy", "Suite 2, 3, 4, 5, Guide Plaza, Alaja, road, Megida, Ayobo, Lagos", "ALIMOSHO", "AYOBO IPAJA", "08163943804"],
    ["Mawucure Pharmacy (Idimu)", "21, Ejigbo road, by Idimu road, Alimosho, Lagos", "ALIMOSHO", "EGBE IDIMU", "08057955653"],
    ["De Omega Healthcare Pharmacy (Igbogila-Ipaja)", "151, Ipaja-Ayobo Road, Igbogila Bus stop, Ipaja, Lagos", "ALIMOSHO", "AYOBO IPAJA", "08115385054"],
    ["Anderson and Naeto Pharmacy", "42, Azeez Karaole Street, Off Oreptal busstop Isheri Alimosho, Lagos", "ALIMOSHO", "IKOTUN/IGANDO", "08023088036"],
    ["Medconnect Pharmacy (Ayobo)", "2, Amule road, Amule bustop, Ayobo, Lagos", "ALIMOSHO", "AYOBO-IPAJA", "08135082187"],
    ["Ajib Pharmacy (Ipaja 1)", "1A, Joel Oyeniyi Street, Off Command Road, Ipaja, Lagos", "ALIMOSHO", "ALIMOSHO", "08141598809"],
    ["Ajib Pharmacy (Ipaja 2)", "12A, Command Road, Ipaja, Lagos", "ALIMOSHO", "ALIMOSHO", "09046127514"],
    ["Lords doing Pharmacy", "12 Olasanoye street off Holy Family hospital Ijegun Satellite town, Lagos", "AMUWO ODOFIN", "ORIADE", "08126962074"],
    ["Royal Treat Index Pharmacy", "1st Avenue 11 Road junction, after Dominos Pizza Festac town", "AMUWO ODOFIN", "AMUWO ODOFIN", "08038613870"],
    ["Victory Drugs", "Plot 57A, 11 Road, Festac Town", "AMUWO ODOFIN", "AMUWO ODOFIN", "08023424425"],
    ["Bolatoks Pharmacy (Amuwo odofin)", "Block 201, Amuwo odofin low cost housing estate, Mile 2, Lagos", "AMUWO ODOFIN", "AMUWO ODOFIN", "08174219342"],
    ["Rosemus Pharmacy (Apapa 1)", "226, Idewu Street, Olodi Apapa, Lagos", "APAPA", "AJEROMI IFELODUN", "08037788345"],
    ["Rosemus Pharmacy (Apapa 2)", "95, Kofo Abayomi street, Apapa, Lagos", "APAPA", "APAPA", "08121261881"],
    ["Bolatoks Pharmacy (Ajegunle)", "11, Rasaki Street, off Agbe Olodi Apapa, Lagos", "APAPA", "AJEROMI IFELODUN", "07032878238"],
    ["Idealcare Pharmacy", "No 1C Aje Street, Along Itoga Zanmu Primary School, Itoga Badagry (Before Itoga Primary School Coming From Mobil Filling Station Or After Itoga Primary School Coming From Limca Bus Stop)", "BADAGRY", "BADAGRY CENTRAL", "08027696380"],
    ["Pharmaways Ltd", "1, Custom Quarters El-King, Ibereko Badagry", "BADAGRY", "OLORUNDA", "08098733372"],
    ["De Royal Treet Pharmacy (Epe)", "39, Ikesan Road, Opposite General Hospital Epe", "EPE", "EPE", "08074484379"],
    ["Empathy Pharmacy (Agbowa- Ikosi)", "Shop 1-4, Complex by 150, Beach road, Ita-Agbowa, Agbowa- Ikosi, Lagos", "EPE", "EPE", "09076703036"],
    ["Bernados Pharmacy (Lekki)", "17b omonrinre Johnson, Lekki Phase 1, Lagos", "ETI-OSA", "ETI OSA", "08056119140"],
    ["Mariam Grey Pharmacy", "Q101, Beachgate Road, Jakande, Lekki, Lagos", "ETI-OSA", "LEKKI", "08090865246"],
    ["Pharmxtra Pharmacy (Chevron drive)", "1, Raliat Omolabi Street, Bera Estate, off Chevron Drive, opposite Atlantic mall, Lekki, Lagos", "ETI-OSA", "ETI OSA", "08184782777"],
    ["Pharmxtra Pharmacy (Ikota 2)", "Road 3, House 49, Ikota Villa Estate, by Mega Chicken, Off lekki Epe express road, Lagos", "ETI-OSA", "ETI OSA", "09066457641"],
    ["Purelife Pharmacy (Lekki 3)", "15b, Admiralty way, by Reddington hospital, Lekki phase 1, Lagos", "ETI-OSA", "ETI OSA", "08090564568"],
    ["Ricmar Pharmacy (Sangotedo 1)", "1 Frank Ojadi close, Sangotedo, Lagos", "ETI-OSA", "ETI OSA EAST", "08071583029"],
    ["Ricmar Pharmacy (Sangotedo 2)", "Fara park estate mall, Fara Park Estate, Sangotedo, Lagos", "ETI-OSA", "ETI OSA EAST", "08033087479"],
    ["Greenvive Pharmacy", "Shop 4, The Courtyard, Ahmed Bus stop, Badore Road, Ajah, Lagos", "ETI-OSA", "ETI OSA EAST", "08033256658"],
    ["Faliko Pharmacy", "A29, Mayfair Gardens Shopping Complex, Awoyaya, Ibeju Lekki, Lagos", "IBEJU-LEKKI", "IBEJU/LEKKI", "08035141014"],
    ["Positive Drugs Pharmacy", "2, Military Estate, Opp Total Filling Station, Eleko Junction, Ibeju Lekki, Lagos", "IBEJU-LEKKI", "IBEJU/LEKKI", "08055222030"],
    ["Essyontop Pharmacy", "12, Oguntona street Ajala bustop Agbado, Ijaiye Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08026473785"],
    ["Bydow Pharmacy (Abule Egba)", "241, Lagos-Abeokuta Expressway, Abule egba (Jendor supermarket), Lagos", "IFAKO IJAIYE", "OJOKORO", "08034087945"],
    ["Bydow Pharmacy (Alagbado)", "No 825, Lagos-Abeokuta Expressway, inside Top Notch Mall, CASO Junction, Alagbado, Lagos", "IFAKO IJAIYE", "OJOKORO", "07060926387"],
    ["Drugmaster Pharmacy (Abule Egba)", "1, Prince Adesua Crescent, agbelekale, Abule Egba, Lagos", "IFAKO IJAIYE", "OJOKORO", "08065519062"],
    ["Massey Vickers Pharmacy (Iju)", "79, Iju Road, Hutoss Super Stores, Agege, Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08150767272"],
    ["Remacon Pharmacy", "2, irepodun Street, off Old Ota Road, Moshalashi, Alagbado, Lagos", "IFAKO IJAIYE", "OJOKORO", "08033330797"],
    ["Zaad Healthcare", "6, Victor Olaleye Road, Rogo Bustop off Iju-Ishaga, Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08063599741"],
    ["Shekinah Specialties (Fagba)", "No 1, Jonathan Coker Street, beside railway crossing, Fagba junction, Lagos state", "IFAKO IJAIYE", "IFAKO-IJAIYE", "07086507796"],
    ["Shekinah Specialties (Olaniyi)", "No 1, Olaniyi street, off agbe road. New oko-oba, Lagos state", "IFAKO IJAIYE", "OJOKORO", "08095589495"],
    ["Shekinah Specialties (Puposola)", "No 9, Amusan street, puposola area. New oko-oba, Lagos state", "IFAKO IJAIYE", "OJOKORO", "08108754799"],
    ["Damilola Olu Pharmacy (Iju 1)", "74, Ahmed Bola Tinubu off station bus-stop Fagba Iju, Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08172702452"],
    ["Damilola Olu Pharmacy (Iju 2)", "2, Ahmed Bola Tinubu off station bus-stop Fagba Iju Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "07066557993"],
    ["Damilola Olu Pharmacy (Obawole)", "49, Kajola obawole off Ahmed Bola Tinubu Fagba Iju Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08032192838"],
    ["Drugrite Pharmacy (Alagbado)", "19, Old Ota Road, Moshalashi Bus stop, Alagbado, Lagos", "IFAKO IJAIYE", "OJOKORO", "08116373932"],
    ["Drugrite Pharmacy (Ijaiye Ojokoro 1)", "12, Agbado Station Road, ijaye Ojokoro, Lagos", "IFAKO IJAIYE", "OJOKORO", "09075721407"],
    ["Drugrite Pharmacy (Ijaiye Ojokoro 2)", "3, Agbado Station Road, Ijaye Ojokoro, Lagos", "IFAKO IJAIYE", "OJOKORO", "08056748647"],
    ["Bydow Pharmacy (Alakuko)", "Jendol Superstores, Odegbami street, off Alh. Ganiyu Oladeinde street, Alakuko, Lagos", "IFAKO IJAIYE", "OJOKORO", "09012510790"],
    ["Lighthouse Pharmacy", "84, Agbado Road, Toyin Bus stop, Iju-Ishaga, Lagos", "IFAKO IJAIYE", "IFAKO-IJAIYE", "08037279350"],
    ["Momaak Pharmacy", "72, Alakuko road, MAO junction, Kola, Lagos", "IFAKO IJAIYE", "OJOKORO", "08033358848"],
    ["Eddylatez Pharmacy", "1, Funsho George shopping complex Amusan, Puposola, New Oko-Oba, Lagos", "IFAKO IJAIYE", "OJOKORO", "08137559007"],
    ["Drugmaster Pharmacy (Ogba)", "51, Ajayi Road, Oke-Ira, Ogba, Lagos", "IKEJA", "OJODU", "07031117515"],
    ["Golby Healthcare", "3, Oladoyinbo street (by Avis B/stop) Aguda-Ogba, Lagos", "IKEJA", "OJODU", "08033066362"],
    ["Healthmax Pharmacy (Anthony)", "1/3 Alade Lawal Street, Anthony village by Anthony Police station, Lagos", "IKEJA", "ONIGBONGBO", "08080765409"],
    ["Healthserveplus Pharmacy (Allen)", "36, Oluwaleyimu Street, off Allen Ikeja, Lagos", "IKEJA", "ONIGBONGBO", "08139404190"],
    ["Healthserveplus Pharmacy (Ikeja)", "1, Toyin Street, Unity Bus Stop, Ikeja, Lagos", "IKEJA", "ONIGBONGBO", "07030384876"],
    ["Santeforte Pharmacy", "7, Bayo Adeshina street, Magodo phase 1, Lagos", "IKEJA", "IKOSI-ISHERI", "08033302312"],
    ["360 Degre Pharmacy (Ogba)", "22 Sonola Street Aguda, Ogba, Lagos", "IKEJA", "OJODU", "080898804567"],
    ["360 Degre Pharmacy (Ojodu)", "14, Ogunnusi Road, Ojodu, Lagos", "IKEJA", "OJODU", "08034980104"],
    ["Shekinah Specialties (Yaya Abatan)", "No 94, Yaya Abatan street, Opposite NNPC filling station, Ogba, Lagos state", "IKEJA", "IFAKO-IJAIYE", "08096783329"],
    ["Hirock Pharmacy", "14, Holiday Inn Road, Of Budland Street, Grammar school bus stop, Ojodu Berger Ikeja LGA, Lagos", "IKEJA", "OJODU", "08023435779"],
    ["Lilac Pharmacy", "12, Oladipo Kuku Street, Off Allen Avenue Ikeja, Lagos", "IKEJA", "ONIGBONGBO", "08033081103"],
    ["Teen Pharmacy", "1B, Badagry Street, Akora Villas, Off Adeniyi Jones Avenue, Ikeja, Lagos", "IKEJA", "ONIGBONGBO", "08165659430"],
    ["Boluke Pharmacy (Ikeja)", "134, Awolowo way, Ikeja, Lagos", "IKEJA", "IKEJA", "08173650512"],
    ["Aquart Pharmacy", "25, itunpate Street opposite Eluku palace ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "08054067616"],
    ["Bydow Pharmacy (Ikorodu)", "KM 2, Ikorodu-ijebu Expressway, Kasholori bustop, Ikorodu, Lagos", "IKORODU", "IKORODU NORTH", "08159557272"],
    ["Columbus Pharmacy", "No 16 bolaji benson street igbo oluwo estate off jumofak bus stop after saint Augustine church ikorodu, Lagos", "IKORODU", "IKORODU WEST", "08030729777"],
    ["Makor Pharmacy (Elepe Ikorodu)", "26, Oba Ijaolu Road, Opposite Elepe Town Hall, By Elepe Bus stop, Elepe, Ikorodu Lagos State", "IKORODU", "IKORODU CENTRAL", "08056967442"],
    ["Makor Pharmacy (Igbe Laara Ikorodu)", "1, Afa Road, beside Igbe Laara Central Mosque, Igbe Laara Bus stop, Igbe Laara, Ikorodu Lagos State", "IKORODU", "IGBOGBO BAIYEKU", "07088567811"],
    ["Promino Pharmacy", "134 Lagos road, Jumofak Bustop, Opposite Conoil filling station Ikorodu, Lagos", "IKORODU", "IKORODU WEST", "08080985204"],
    ["Sybarmedics Pharmacy", "1, Agbede Olorogbo bustop off Asolo bustop by Isawo rd, Agric Ikorodu, Lagos", "IKORODU", "IKORODU WEST", "08033405568"],
    ["Pauprix Pharmacy (Adamo)", "16, Araromi rd, Adamo, Ikorodu, Lagos", "IKORODU", "IKORODU NORTH", "09066072700"],
    ["Pauprix Pharmacy (Haruna)", "116, Haruna Bustop, Ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "08185073641"],
    ["Pauprix Pharmacy (Ita- Oluwo)", "26, Ajegunle Road, Ita-Oluwo Ikorodu, Lagos", "IKORODU", "IKORODU WEST", "07082820343"],
    ["May & Flora Pharmacy", "202, Obafemi Awolowo Road, Itamaga Roundabout, Itamaga, Ikorodu, Lagos,", "IKORODU", "IKORODU NORTH", "08174600480, 08033817905"],
    ["Totem Pharmacy (Ikorodu)", "Shop 29, JAF Plaza, Estate Junction, Odonla road, Odonla Ikorodu, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "08033538044"],
    ["Winlot Pharmacy", "49, along Ijede road, beside Just 4 you Eatery, Eleshin car wash, Eleshin Elepe, Ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "08054320943"],
    ["Frontliner Pharmacy", "1, Almaroof junction by T.J Bustop, Ayanfalu Estate, Offin-ile, Igbogbo, Ikorodu, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "08037161469"],
    ["Constanstar Pharmacy (Ibeshe)", "No 1, Rabaka Street, owode, Ibeshe, ikorodu, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "08033787143"],
    ["Constanstar Pharmacy (Igbo Agbowa)", "32, Awolegun Road, Igbo Agbowa, Off Ebute- Igbogbo Road, Ikorodu, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "07034404849"],
    ["Constanstar Pharmacy (Igbogbo)", "Macaulay bus stop, Bayeiku, Igbogbo Road, Ikorodu, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "08032328023"],
    ["Helix Pharmacy", "67, Ayangburen Road by Olubi street, Ojogbe, Ikorodu, Lagos.,", "IKORODU", "IKORODU CENTRAL", "08033580590, 08167288814"],
    ["Hugies Pharmacy", "39, Bola Ahmed Tinubu Way, Opposite Cele Church, beside Igbogbo stadium, Igbogbo, Lagos", "IKORODU", "IGBOGBO BAIYEKU", "08153911538"],
    ["Temidara Pharmacy", "2, Suberu Ogunsanya street beside Oba Ayangburen Palace before Solomade Gate, Ikorodu Garage, Ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "08035725969"],
    ["Empathy Pharmacy (Gberigbe 1)", "AP bustop along, Gberigbe road, Gbodu, Ikorodu, lagos", "IKORODU", "IKORODU CENTRAL", "08064537095"],
    ["Empathy Pharmacy (Gberigbe 2)", "CAC bustop, along Agura-Gberigbe road, Gberigbe, Ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "07061925876"],
    ["Glorious Health Pharmacy", "No 1, Oloja street, white house bus stop, odogunyan ikorodu, Lagos", "IKORODU", "IKORODU NORTH", "09061478603"],
    ["Macojo Pharmacy (TOS Benson)", "13, TOS Benson Road, Ojogbe Bustop, Along General Hospital Road, Ikorodu, Lagos", "IKORODU", "IKORODU CENTRAL", "08035824575"],
    ["Remedy Drugs Plus", "4, NBC road, Ebute, Ikorodu, Lagos", "IKORODU", "IKORODU WEST", "08023320671"],
    ["Skype Pharmacy", "263, Oreyo igbe road, Igbogbo Ikorodu, Lagos", "IKORODU", "IGBOGBO-BAIYEKU", "07066417263"],
    ["Healthserveplus Pharmacy (Anthony)", "4, Alhaja Oluwakemi Street, Anthony Village Maryland, Lagos", "KOSOFE", "KOSOFE", "08107885655"],
    ["Trudrug Pharmacy", "No 35 Olowora road, Olawaye model shops (opposite owokade junction), Olowora, Berger, Lagos", "KOSOFE", "OJODU", "08033454869"],
    ["Mawucure Pharmacy (Oworoshoki)", "89, Oworo road, by L & K Bustop, Oworoshoki, Kosofe, Lagos", "KOSOFE", "KOSOFE", "08057955653"],
    ["Promino Pharmacy (Ogudu)", "58 Agboyi road, Ogudu orioke, Lagos", "KOSOFE", "AGBOYI KETU", "08080985204"],
    ["Dhello Pharmacy", "49, Davies Street, Ketu, Lagos.,", "KOSOFE", "AGBOYI KETU", "08179038549, 08100700569"],
    ["Lagos Island Pickup Centre", "215, Igbosere road, Lagos Island, Lagos", "LAGOS ISLAND", "LAGOS ISLAND EAST", "08064275976"],
    ["Ariox Pharmacy", "55, Kano Street off osholake street on Longford Secondary school road, Ebute meta, Lagos mainland LGA, Lagos state", "LAGOS MAINLAND", "LAGOS MAINLAND", "08033827512"],
    ["Habibi Pharmacy (Akoka)", "21 Abayomi Street, Akoka, Lagos", "LAGOS MAINLAND", "SHOMOLU", "08034526600"],
    ["League Pharmacy", "289, Herbert Macaulay Way, opposite Mallmart and Sterling bank, Alagomeji, Yaba, Lagos", "LAGOS MAINLAND", "YABA", "08022014939"],
    ["Nedol Pharmacy", "9, Carter Street Ebute Metta by Mainland mosque or Evans Square, Lagos", "LAGOS MAINLAND", "LAGOS MAINLAND", "08037256283"],
    ["Okolowhite Pharmacy", "1, Birrel Avenue, near Yaba Magistrate Court, Sabo- Yaba, Lagos", "LAGOS MAINLAND", "YABA", "08033217034"],
    ["Oliveheight Pharmacy", "113, Apata Road, Ebute Meta, Lagos", "LAGOS MAINLAND", "LAGOS MAINLAND", "07036616909"],
    ["Pharmasolutions (Alagomeji)", "Amazing Grace Plaza, 23 Hughes Avenue, Alagomeji, Yaba, Lagos", "LAGOS MAINLAND", "YABA", "08104931060"],
    ["Pharmasolutions (Sabo)", "28, Commercial Avenue, Sabo Yaba, Lagos", "LAGOS MAINLAND", "YABA", "08091111608"],
    ["Hope-Cee Pharmacy", "6, Thomas Street, Ebute-Metta West, Lagos", "LAGOS MAINLAND", "LAGOS MAINLAND", "08037154747"],
    ["All day Pharmacy (Mushin 1)", "12 Sadiku Street, Ilasamaja, Mushin, Lagos", "MUSHIN", "MUSHIN", "08033308116"],
    ["All day Pharmacy (Mushin 2)", "02, Da Silva Avenue, Off Alafia Street, Ilasamaja Mushin, Lagos", "MUSHIN", "MUSHIN", "08032961400"],
    ["Highrise Pharmacy (Mushin)", "34, Iyalla street, Mushin, Lagos", "MUSHIN", "MUSHIN", "08036375145"],
    ["Flinty Rock Pharmacy&stores", "13, Isashi Road, Mebamu Badagry Expressway Road, Lagos", "OJO", "IBA", "08029990318"],
    ["Tonag Pharmaceuticals (Badagry)", "1, Chief Esan Way, Church Estate, Church Bus Stop, Badagry Expressway, Lagos", "OJO", "OTTO AWORI", "07039885379"],
    ["Comely Anchor Pharmacy", "12 Owoseni Street behind ijaniki police station ijanikin, Lagos", "OJO", "OTTO AWORI", "08128199744"],
    ["Decency Care Pharmacy", "No 45/46, Zone 4 Road, By Army Check Point, Victory Estate, Iba Ojo, Lagos", "OJO", "IBA", "09071582540"],
    ["Elbeth Pharmacy", "28, Celestial road, oluwatedo estate, Isashi (next street after Water Corporation) Ojo LGA, Lagos", "OJO", "IBA", "08086536125"],
    ["Felimat Pharmacy (Agbara)", "07 Agbara Shopping Mall, 01 Agbara Estate Road, off Lagos Badagry Expressway, Agbara Bus stop, Lagos", "OJO", "OTTO AWORI", "08060790458"],
    ["Felimat Pharmacy (Ojo)", "Km 173 Lagos Badagry Expressway Volks Bus stop, near the pedestrian bridge before Mobil filling Station, Ojo, Lagos", "OJO", "OTTO AWORI", "08031334587"],
    ["Jedidiah Community Pharma Plus", "36 Adaloko Road, off Iyana Era bus stop, Adjacent Gabriel junction on Adaloko Road, Ijanikin, Lagos", "OJO", "OTTO AWORI", "08039648778"],
    ["Kenson Jones Pharmacy", "15, Akere street, okokomaiko market bustop, opp Mary plaza, Okokomaiko, Ojo, Lagos", "OJO", "OTTO AWORI", "07063420455"],
    ["Klickfit Pharmacy", "2b Adebayo Street, off Ejike Street, white house b/stop Okokomaiko Ojo, Lagos", "OJO", "IBA", "07038202746"],
    ["Koel Community Healthcare Ltd", "20, Gbadamosi street, Igboelerin, Iba LCDA, Ojo, Lagos", "OJO", "IBA", "08086681865"],
    ["Newton Pharmacy (LASU- IBA)", "Suite 3&4, Adoff Bus stop, Along Iba-Lasu Express way, Iba, Lagos", "OJO", "IBA", "08066558367"],
    ["Taigab Pharmacy", "20, Etegbin Road, Shibiri, Ojo LGA, Lagos", "OJO", "OTTO AWORI", "08033040031"],
    ["Verjoe Pharmacy", "1, Omotosho street, off People's B/Stop, Ojo, Alaba, Ojo Local Government Area, Ojo, Lagos", "OJO", "OJO", "08062827559"],
    ["Tonag Pharmaceuticals (Ojo)", "40, Baale Street, Afromedia Road, Opposite Okosun Street, a.k.a Ijeoma Pharmacy, Ojo, Lagos", "OJO", "OJO", "08023673328"],
    ["Biotech Systems & Pharmaceuticals", "7/9 Baale Road, Afromedia, Ajangbadi, Opposite Moko Company/New Healthway Company, Ojo, Lagos", "OJO", "OJO", "08035005950"],
    ["Massey Vickers Pharmacy (Iba)", "Twinsfaja Plaza, Ipaye Bus stop, Iba Road, Lagos", "OJO", "IBA", "08168590160"],
    ["Sinews and Muscles Pharmacy", "101 Era Road Adele bus Stop off Iyana Era Bus Stop Lagos Badagry Expressway, Ijanikin Oto-Awori Ojo- Lagos", "OJO", "OTTO AWORI", "08034859995"],
    ["Lopez Pharmacy", "10 Omila Road, Onireke, Ojo, Lagos", "OJO", "IBA", "08135459018"],
    ["ABJ Pharmacy", "193/195, Ago Palace Way, Okota, Lagos", "OSHODI-ISOLO", "ISOLO", "08053019458"],
    ["All Gate Pharmacy", "116, Mushin Road, Opposite Total Filling Station, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "08036728207"],
    ["Baykay Pharmacy", "2, Adelaja Street, by Afariogun street, charity oshodi, Lagos", "OSHODI-ISOLO", "OSHODI ISOLO", "08055350149"],
    ["Multimed Pharmacy", "3, Sir Ben Onyeka Street, Greenfield Estate, Okota, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "08053019458"],
    ["Nesfield Pharmacy (Jakande Oke Afa 1)", "Opposite Oja Bus stop, Jakande Estate Oke-Afa, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "08037175032"],
    ["Nesfield Pharmacy (Jakande Oke Afa 2)", "289 Pink Bungalow, Jakande Estate Oke Afa, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "09070973860"],
    ["Pedov Healthcare", "37 Ajibulu Street, Mafoluku Oshodi, off Airport road by Eweje street, after Ajibulu primary school, Lagos", "OSHODI-ISOLO", "OSHODI ISOLO", "08035875519"],
    ["Prezzy Pharmacy", "234, Ago palace way Okota by Indigo bar, Christ Embassy bustop, Oshodi-Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "07068342292"],
    ["Turmeric Pharmacy (Isolo)", "41, Ire-Akari Estate Road, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "08066295711"],
    ["WestEast Pharmacy", "36, Okeho street, Opposite St. Mary's Catholic Church Ire Akari Estate Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "08062812127"],
    ["Stairway Pharmacy (Isolo)", "No 45 Ugali Street Ishaga busstop off Isolo Mushin Road Ire Akari Estate near Ire Akari police station Isolo Lagos", "OSHODI-ISOLO", "ISOLO", "08063641848"],
    ["Welnex Pharmacy (Jakande Oke Afa)", "9, Egbe Road, Oke afa Isolo, by Benson Akinyele Street, Jakande, Lagos", "OSHODI-ISOLO", "ISOLO", "07032112589"],
    ["Welnex Pharmacy (Oshodi)", "32 Sehinde Calisto (Ewenla) Street, Opposite Marblefield Hotel, Lagos", "OSHODI-ISOLO", "ISOLO", "07086830812"],
    ["Netlink Pharmacy", "22, Peter Agha Street, Oke Afa, Isolo, Lagos", "OSHODI-ISOLO", "ISOLO", "0806273546"],
    ["Octavia Pharmacy", "33, Okuta Road, Ilaje Bustop, Opposite Ilaje Health Center, Bariga, Lagos", "SHOMOLU", "BARIGA", "07067173821"],
    ["Robson Pharmaceuticals Ltd", "16, Oresegun Crescent, Bariga, Lagos", "SHOMOLU", "BARIGA", "08033432538"],
    ["Wryte Med Pharmacy", "Good Plaza, Opposite Ecobank, Apata Bus stop, Shomolu, Lagos", "SHOMOLU", "BARIGA", "08037205145"],
    ["Pinco Pharmacy", "111, Igi Olugbin Street, Pedro Road, by Awofodu Bus stop, Bariga, Lagos", "SHOMOLU", "BARIGA", "08023444408"],
    ["Bernados Pharmacy (Idi- araba)", "65A Ishaga road opp LUTH Access bank, idi-araba bustop, Lagos", "SURULERE", "ODI-OLOWO", "07025504816"],
    ["Biotrust Pharmacy", "43, Bode Thomas Street, Surulere, Lagos", "SURULERE", "SURULERE", "0803151930"],
    ["Dexta Health Pharmacy", "29c, Itire Road, Close to Randle traffic light on municipal busstop, Surulere, Lagos", "SURULERE", "ITIRE/IKATE", "08063792806"],
    ["Kayton Pharmacy", "118 Akerele Street, next to House of Phreedah, Surulere, Lagos", "SURULERE", "SURULERE", "09063508688"],
    ["Silverline Pharmacy", "18, Olatunde Onimole Street, Aguda, Surulere, Lagos", "SURULERE", "COKER/AGUDA", "09094951752"],
    ["Vita Chemists Ltd", "75, Tejuosho Street, Surulere, Lagos", "SURULERE", "SURULERE", "08033025138"],
    ["Wellberth Pharmacy", "36, Benson Street, off Akerele, Surulere, Lagos", "SURULERE", "SURULERE", "08037367470"],
    ["Karadin Pharmacare (Surulere)", "No 11, Abu Street, Coker-Orile Surulere, Lagos", "SURULERE", "ITIRE/IKATE", "0806513106"],
    ["Nunchimerak Pharmacy", "9 Akin-Delu Street, Ikate, Surulere, Lagos", "SURULERE", "ITIRE/IKATE", "08023130690"],
    ["Oyetol Pharmacy", "No 6 Anjorin Lawanson, Surulere, Lagos", "SURULERE", "ITIRE/IKATE", "08032842357"],
    ["Boluke Pharmacy (Surulere)", "17, Adebola Ojomu Street, Aguda Surulere, Lagos", "SURULERE", "COKER/AGUDA", "0817420949"],
    ["Megosa Healthcare", "23, Yisa Oroki Street, Coker Bridge, Surulere, Lagos", "SURULERE", "ITIRE/IKATE", "08037154747"]
];

const jaaraPlusTable = [
    ["ANCILLA CATHOLIC HOSPITAL, AGEGE", "113, ODUMOSU CLOSE, IFAKO, AGEGE", "AGEGE"],
    ["BIO BATAM HOSPITAL", "53, TIJANI STREET, IYANA IPAJA", "AGEGE"],
    ["DUNIA HOSPITAL LTD", "45, OKO-OBA ROAD, AGEGE", "AGEGE"],
    ["PROMISE MEDICAL CENTRE", "132 DOPEMU ROAD, DOPEMU, AGEGE", "AGEGE"],
    ["R-JOLAD HOSPITAL (SALEM HOUSE)", "23/24 OMOTOYE ESTATE ROAD, OFF IPAJA ROAD, MULERO BUS-STOP, ORILE-AGEGE", "AGEGE"],
    ["ALL SOULS' HOSPITAL", "255 OJO ROAD, SURU ALABA, MILE 2, AJEGUNLE, APAPA", "AJEROMI-IFELODUN"],
    ["DE-OVERCOMING GRACE HOSPITAL", "19, MUDA STREET, AMUKOKO", "AJEROMI-IFELODUN"],
    ["FALETI MEDICAL CENTRE", "98 BAALE STREET, OLODI, APAPA", "AJEROMI-IFELODUN"],
    ["ADEBAYO SPECIALIST HOSPITAL", "14, AJENIFUJA STREET, GOVERNOR'S ROAD, IKOTUN", "ALIMOSHO"],
    ["ARABA MEDICAL CENTRE", "122, EKORO AGBELEKALE ROAD, ABULE-EGBA, ALIMOSHO", "ALIMOSHO"],
    ["CRYSTAL SPECIALIST HOSPITAL", "148/150 AKOWONJO ROAD, EGBEDA", "ALIMOSHO"],
    ["HAMKAD HOSPITAL NIGERIA LIMITED", "39, OLAWALE COLE STREET, ABULE-EGBA, ALIMOSHO", "ALIMOSHO"],
    ["KROWN HOSPITAL", "11, ALHAJI SEKONI STREET, OFF ALIMOSHO ROAD, IYANA-IPAJA", "ALIMOSHO"],
    ["LIGHT HOSPITAL & MATERNITY HOME LTD", "15, OLUMIDE ONANUBI STREET, ALIMOSHO BUS STOP, ALIMOSHO", "ALIMOSHO"],
    ["MERCY STRIPES SPECIALIST HOSPITAL", "30, PHILIP TAIWO STREET, ORISUMBARA-SHASHA, ALIMOSHO", "ALIMOSHO"],
    ["MOTHER TERESA MEDICAL CENTER", "107, LIASU ROAD, IDIMU, EGBE", "ALIMOSHO"],
    ["SUBOL HOSPITAL LIMITED", "16/17 OBA AMUSAN AVENUE, IDIMU", "ALIMOSHO"],
    ["WESTCARE SPECIALIST HOSPITAL", "32, SAMUEL STREET, VULCANIZER BUS STOP, AKOWONJO", "ALIMOSHO"],
    ["FIRSTLINE HOSPITAL, FESTAC", "2ND AVENUE, HOUSE 14, BY 207 JUNCTION, FESTAC", "AMUWO-ODOFIN"],
    ["GOLDEN CROSS INFIRMARY HOSPITAL & MATERNITY", "2ND AVENUE, 22 ROAD, FESTAC TOWN, AMUWO-ODOFIN", "AMUWO-ODOFIN"],
    ["ST. MILLA HOSPITAL", "19 A, LADIPO OLUWOLE STREET, APAPA GRA, APAPA", "APAPA"],
    ["SYBAN MEDICAL CENTRE", "33 ADEKUNLE DEEN STREET, SARI-IGANMU, APAPA", "APAPA"],
    ["IBIJOLA MEDICAL CENTRE", "OFF KM 34 LAGOS BADAGRY EXPRESSWAY, UNITY ESTATE, GADDA, IBIYE, OLORUNDA LCDA, BADAGRY", "BADAGRY"],
    ["WELL EAGLE HEALTH SERVICES LTD", "BEHIND RCCG (GRACELAND PARISH), JAH MICHAEL BUS-STOP, MAGBON, BADAGRY", "BADAGRY"],
    ["MOUNT PARAN HOSPITAL", "6, IDOWU APETE STREET, OFF PELEYEJU STREET, URAKA, EPE", "EPE"],
    ["BESTCARE HOSPITAL LIMITED", "2A, KEFFI STREET, SOUTHWEST, IKOYI", "ETI-OSA"],
    ["J RAPHA HOSPITAL", "40, ADDO LAMGBASA ROAD, BAKARE BUS STOP, AJAH", "ETI-OSA"],
    ["THE ROYAL INFIRMARY HOSPITAL", "BAKERY BUS/STOP, ALONG BADORE ADDO ROAD, AJAH", "ETI-OSA"],
    ["GOFEE HOSPITAL LTD", "HOUSE 5, ROAD 2B, MARKET STREET, OFF OGUNFOYE PALACE ROAD, EPUTU", "IBEJU-LEKKI"],
    ["OCEANSIDE HOSPITAL", "15, ACHIEVERS COMMUNITY, ELEPETE", "IBEJU-LEKKI"],
    ["TRANSAQUATIC HOSPITAL", "KM 35, LEKKI-EPE EXPRESS WAY, OPP. TOYOTA AUTO NATION, BOGIJE", "IBEJU-LEKKI"],
    ["ANTHONY CARDINAL OKOGIE'S MEDICAL CENTER", "7, ADE-OMINUGA STREET, NEW OKO OBA, AGEGE", "IFAKO-IJAIYE"],
    ["BLOOMING CARE HOSPITAL", "30, BAALE ANIMASHAUN ROAD, ALAKUKO, IFAKO-IJAIYE", "IFAKO-IJAIYE"],
    ["JEFIS SPECIALIST HOSPITAL", "9, ADEGBOLA STREET, OFF BAALE ANIMASHAUN ROAD, ALAKUKO", "IFAKO-IJAIYE"],
    ["LONGING MEDICAL CENTRE", "3-5, JOSEPHA CLOSE, OFF OGUNDEJI OGUNTONA STREET, AJALA BUS-STOP, IJAIYE-OJOKORO", "IFAKO-IJAIYE"],
    ["OSUNTUYI MEDICAL CENTER, IJU", "225, IJU ROAD, IFAKO-IJAIYE", "IFAKO-IJAIYE"],
    ["COUNTY HOSPITAL LIMITED", "43/45, ISHERI ROAD, AGUDA, OGBA", "IKEJA"],
    ["MOTAYO HOSPITAL LIMITED", "3, OWODUNNI STREET, OFF TOYIN STREET, IKEJA", "IKEJA"],
    ["ALHERI HOSPITAL, IKORODU", "60, AGUNFOYE ROAD, AKANUN ADAMO BUS STOP, IKORODU", "IKORODU"],
    ["ARUNA OGUN MEMORIAL SPECIALIST HOSPITAL", "2/4, BAMIMOSU STREET, EBUTE, IKORODU", "IKORODU"],
    ["BERNICE HOSPITAL", "318, LAGOS ROAD, OGOLONTO BUS-STOP, BESIDE BRT BRIDGE, OGOLONTO", "IKORODU"],
    ["CUTE HEALTHCARE LTD", "190, IRE ROAD, IRE AGUNFOYE, IGBOGBO", "IKORODU"],
    ["DASOCHRIS HOSPITAL", "2ND AVENUE, PABOYEJO ESTATE, BEHIND HOSANNA CHAPEL ALONG ODONLA, ODOGUNYAN", "IKORODU"],
    ["EBUNOLUWA HOSPITAL", "11, GBASEMO STREET, AGAA", "IKORODU"],
    ["JOBI CLINIC AND MATERNITY HOSPITAL LTD", "3/5 ADEYERI OWUYI STREET, IKORODU", "IKORODU"],
    ["LIFESOURCE HOSPITAL", "9, CHURCHILL EMENIKE STREET, CRYSTAL ESTATE, OFF MOWO-NLA ROAD, JAJO, IJEDE", "IKORODU"],
    ["ST RAPHAEL DIVINE MERCY SPECIALIST HOSPITAL", "BOJE TOWN, IJEDE ROAD, IKORODU", "IKORODU"],
    ["MED-IN SPECIALIST HOSPITAL", "1/3 OSGBO STREET, OGUDU, OJOTA", "KOSOFE"],
    ["ST. NICHOLAS HOSPITAL, MARYLAND", "18, FARAMOBI AJIKE CRESCENT, OFF IKORODU ROAD", "KOSOFE"],
    ["ST NICHOLAS HOSPITAL", "57, CAMPBELL STREET, LAGOS ISLAND", "LAGOS ISLAND"],
    ["THE HEALTH ARENA SPECIALIST CLINICS HOSPITAL & MATERNITY HOME", "12B, STRACHAN STREET, ORLANDO MARTINS, LAGOS ISLAND EAST", "LAGOS ISLAND"],
    ["COTTAGE MEDICARE HOSPITAL", "18, IWAYA ROAD, ONIKE, YABA", "LAGOS MAINLAND"],
    ["FEDERAL MEDICAL CENTER, EBUTE-METTA", "RAILWAY COMPOUND, EBUTE-METTA", "LAGOS MAINLAND"],
    ["FIRST HERITAGE MEDICARE SERVICES LTD", "29/33, AYANTUGA STREET, OLORUNSOGO, MUSHIN", "MUSHIN"],
    ["HILLSTAR CLINICS (NIG) LTD", "98, PALM AVENUE, MUSHIN", "MUSHIN"],
    ["HEALING LAND HOSPITAL", "106, OKE-AGBO ROAD, OKE-AGBO", "OJO"],
    ["KILADEJO HOSPITAL AND SPECIALIST CLINICS", "15, PPL ROAD, OFF BADAGRY EXPRESSWAY, OKOKOMAIKO, OJO", "OJO"],
    ["DIALYZER MEDICAL CENTRE", "60, AROWOJOBE STREET, OSENI BUS STOP, OSHODI", "OSHODI-ISOLO"],
    ["DIVINE GRACE HEALING STRIPES HOSPITAL", "3, SHOBOGUN ROFA STREET, MAFOLUKU, OSHODI", "OSHODI-ISOLO"],
    ["ONELIFE HOSPITAL", "485, AGEGE MOTOR ROAD, BOLADE-OSHODI, OSHODI-ISOLO", "OSHODI-ISOLO"],
    ["WESTCARE HOSPITAL-EJIGBO", "31, IFOSHI ROAD, PIPELINE BUS STOP, OPPOSITE CHRISLAN MOSQUE, ORILOWO AREA, EJIGBO", "OSHODI-ISOLO"],
    ["ANIYUN HOSPITALS LIMITED", "3, FEMI ADERIBIGBE CLOSE, OFF DIYA STREET, IFAKO, GBAGADA", "SHOMOLU"],
    ["OSUNTUYI MEDICAL CENTER, OBANIKORO", "9, ALHAJI SALISU STREET, OBANIKORO", "SHOMOLU"],
    ["HIS STRIPES SPECIALIST HOSPITAL", "19, SAVAGE STREET, ORILE IGANMU, SURULERE", "SURULERE"],
    ["MERCY THOMAS OREDUGBA MEDICAL & DENTAL CENTRE", "8, MOGAJI STREET, IJESATEDO, OFF PAKO AGUDA, ITIRE-IKATE LCDA", "SURULERE"]
];

  const toggleTable = (table) => {
    setVisibleTable(visibleTable === table ? null : table);
  };

  const handleSort = (table, key) => {
    setSortConfig((prev) => {
      const newDirection = prev[table].key === key && prev[table].direction === 'asc' ? 'desc' : 'asc';
      return { ...prev, [table]: { key, direction: newDirection } };
    });
  };

  const handleFilter = (table, value) => {
    setFilterText((prev) => ({ ...prev, [table]: value }));
    setCurrentPage((prev) => ({ ...prev, [table]: 1 }));
  };

  const handleLGAFilter = (table, value) => {
    setSelectedLGA((prev) => ({ ...prev, [table]: value }));
    setCurrentPage((prev) => ({ ...prev, [table]: 1 }));
  };

  const sortData = (data, table) => {
    if (!sortConfig[table].key) return data;
    const sortedData = [...data].sort((a, b) => {
      const valueA = a[sortConfig[table].key].toLowerCase();
      const valueB = b[sortConfig[table].key].toLowerCase();
      if (valueA < valueB) return sortConfig[table].direction === 'asc' ? -1 : 1;
      if (valueA > valueB) return sortConfig[table].direction === 'asc' ? 1 : -1;
      return 0;
    });
    return sortedData;
  };

  const filterData = (data, table) => {
    let filteredData = data;
    if (filterText[table]) {
      filteredData = filteredData.filter((row) =>
        row.some((cell) => cell.toLowerCase().includes(filterText[table].toLowerCase()))
      );
    }
    if (selectedLGA[table]) {
      filteredData = filteredData.filter((row) => row[2] === selectedLGA[table]);
    }
    return filteredData;
  };

  const handlePageChange = (table, direction) => {
    setCurrentPage((prev) => ({
      ...prev,
      [table]: prev[table] + direction,
    }));
    window.scrollTo(0, 0);
  };

  const getPaginatedData = (data, table) => {
    const startIndex = (currentPage[table] - 1) * rowsPerPage;
    return data.slice(startIndex, startIndex + rowsPerPage);
  };

  const getPageCount = (data) => Math.ceil(data.length / rowsPerPage);

  const getUniqueLGAs = (data) => {
    const lgas = data.map((row) => row[2]);
    return [...new Set(lgas)].sort();
  };

  const renderTable = (tableId, data, headers, title) => {
    const filteredData = filterData(sortData(data, tableId), tableId);
    const paginatedData = getPaginatedData(filteredData, tableId);
    const pageCount = getPageCount(filteredData);
    const uniqueLGAs = getUniqueLGAs(data);

    return (
      <div className="mb-6">
        <div
          className="flex items-center justify-between p-4 bg-gray-100 rounded shadow cursor-pointer"
          onClick={() => toggleTable(tableId)}
        >
          <h3 className="text-lg font-medium">{title}</h3>
          <span
            className={`text-orange-500 transform transition-transform ${visibleTable === tableId ? 'rotate-90' : ''}`}
          >
            <i className="fa-solid fa-arrow-right-long"></i>
          </span>
        </div>
        {visibleTable === tableId && (
          <div className="p-4 mt-4 bg-white rounded shadow">
            <div className="flex flex-col sm:flex-row sm:items-center sm:space-x-4 mb-4">
              <input
                type="text"
                placeholder="Search..."
                value={filterText[tableId]}
                onChange={(e) => handleFilter(tableId, e.target.value)}
                className="w-full sm:w-1/2 p-2 border border-gray-300 rounded"
              />
              <select
                value={selectedLGA[tableId]}
                onChange={(e) => handleLGAFilter(tableId, e.target.value)}
                className="w-full sm:w-1/2 p-2 border border-gray-300 rounded mt-2 sm:mt-0"
              >
                <option value="">All LGAs</option>
                {uniqueLGAs.map((lga) => (
                  <option key={lga} value={lga}>{lga}</option>
                ))}
              </select>
            </div>
            <table className="w-full border border-collapse border-gray-200 table-auto">
              <thead>
                <tr>
                  {headers.map((header, index) => (
                    <th
                      key={index}
                      className="p-2 border border-gray-300 cursor-pointer hover:bg-gray-100"
                      onClick={() => handleSort(tableId, index)}
                    >
                      {header}
                      {sortConfig[tableId].key === index && (
                        <span>{sortConfig[tableId].direction === 'asc' ? ' ↑' : ' ↓'}</span>
                      )}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {paginatedData.map((row, idx) => (
                  <tr key={idx}>
                    {row.map((cell, index) => (
                      <td key={index} className="p-2 border border-gray-300">{cell}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="flex items-center justify-between mt-4">
              <button
                onClick={() => handlePageChange(tableId, -1)}
                disabled={currentPage[tableId] === 1}
                className="px-4 py-2 text-gray-700 bg-gray-300 rounded disabled:opacity-50 hover:bg-gray-700 hover:text-white transition"
              >
                Previous
              </button>
              <span>
                Page {currentPage[tableId]} of {pageCount}
              </span>
              <button
                onClick={() => handlePageChange(tableId, 1)}
                disabled={currentPage[tableId] === pageCount}
                className="px-4 py-2 text-gray-700 bg-gray-300 rounded disabled:opacity-50 hover:bg-gray-400 hover:text-white transition"
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="container py-10 pt-40 mx-auto">
      <h2 className="mb-6 text-2xl font-semibold text-center">View Providers</h2>
      {renderTable('table1', table1Data, ['Provider Name', 'Address', 'LGA'], 'Standard Jaara Plan Hospital')}
      {renderTable('table3', jaaraPlusTable, ['Provier Name', 'Address', 'LGA'], 'Standard Jaara Plus Plan Hospital')}
      {renderTable('table2', table2Data, ['Pharmacy Name', 'Address', 'LGA', 'LCDA', 'Phone Number'], 'Community Pharmacy')}
    </div>
  );
};

export default Provider;
